In [2]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.compose import make_column_selector, make_column_transformer
from sklearn.linear_model import (
    ElasticNet,
    Lasso,
    LinearRegression,
    Ridge,
    ridge_regression,
)
from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, PolynomialFeatures

# Set working directory (using a raw string to avoid escape character issues with backslashes)
os.chdir(
    r"E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets"
)

In [5]:
housing = pd.read_csv('Housing.csv')
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [11]:
dum_hous = pd.get_dummies(housing, drop_first = True)
dum_hous

,price,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,42000.0,5850,3,1,2,1,True,False,True,False,False,False
1,38500.0,4000,2,1,1,0,True,False,False,False,False,False
2,49500.0,3060,3,1,1,0,True,False,False,False,False,False
3,60500.0,6650,3,1,2,0,True,True,False,False,False,False
4,61000.0,6360,2,1,1,0,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,0,True,True,False,False,True,False
542,94000.0,6000,3,2,4,0,True,False,False,False,True,False
543,103000.0,6000,3,2,4,1,True,True,False,False,True,False
544,105000.0,6000,3,2,2,1,True,True,False,False,True,False
545,105000.0,6000,3,1,2,1,True,False,False,False,True,False

In [15]:
X , y = dum_hous.drop('price', axis =1) , dum_hous['price']

X_train , X_test , y_train, y_test = train_test_split(X,y,random_state = 26 , test_size = 0.3)
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
r2_score(y_test, y_pred)

0.6791781818067918

In [19]:
tst_Housing = pd.read_csv('tst_Housing.csv')
tst_Housing

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,5600,3,1,2,yes,no,yes,no,no,1,no
1,4355,2,1,1,yes,no,no,no,no,0,no
2,3412,3,1,1,yes,no,no,no,no,0,no
3,6666,2,2,2,yes,yes,no,no,no,0,no

In [36]:
dm = pd.get_dummies(tst_Housing ) 
dm = pd.get_dummies(tst_Housing, drop_first = True) # if pass drop_first then problem that cols miss. which has same values no
dm

# y_pred = lr.predict(dm)
# y_pred

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_no,recroom_yes,fullbase_no,fullbase_yes,gashw_no,airco_no,prefarea_no
0,5600,3,1,2,1,True,True,False,False,True,True,True,True
1,4355,2,1,1,0,True,True,False,True,False,True,True,True
2,3412,3,1,1,0,True,True,False,True,False,True,True,True
3,6666,2,2,2,0,True,False,True,True,False,True,True,True

In [50]:
# ==================================================================================================================

In [38]:
# solution
# datasets
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [51]:

x = housing.drop('price', axis=1)
y = housing['price']

ohc = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')

ct = make_column_transformer(
                            (ohc,           make_column_selector(dtype_include = object)),
                            ('passthrough', make_column_selector(dtype_include =['int64','float64'])),
                             verbose_feature_names_out = False)
ct = ct.set_output(transform = 'pandas')
x_ohe = ct.fit_transform(x)



X_train , X_test , y_train, y_test = train_test_split(x_ohe,y,random_state = 26 , test_size = 0.3)
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
# r2_score(y_test, y_pred)

tst_Housing = pd.read_csv('tst_Housing.csv')
testd = ct.transform(tst_Housing)
pred = lr.predict(testd)

print("After testing data: ")
tst_Housing['pred'] = pred
tst_Housing # after prediction

After testing data:

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea,pred
0,5600,3,1,2,yes,no,yes,no,no,1,no,66460.253302
1,4355,2,1,1,yes,no,no,no,no,0,no,42714.874647
2,3412,3,1,1,yes,no,no,no,no,0,no,40469.900144
3,6666,2,2,2,yes,yes,no,no,no,0,no,75958.607124

In [52]:
tst_Housing = pd.read_csv('tst_Housing.csv')
testd = ct.transform(tst_Housing)
pred = lr.predict(testd)

pred

array([66460.25330163, 42714.87464687, 40469.90014429, 75958.60712357])