In [2]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.compose import make_column_selector, make_column_transformer
from sklearn.linear_model import (
    ElasticNet,
    Lasso,
    LinearRegression,
    Ridge,
    ridge_regression,
)
from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, PolynomialFeatures

# Set working directory (using a raw string to avoid escape character issues with backslashes)
os.chdir(
    r"E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Medical_Cost_Personal"
)

In [3]:
df = pd.read_csv('insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [6]:
x,y = df.drop('charges', axis=1), df['charges']

X_train, X_test, y_train, y_test = train_test_split(x,y,random_state=26, test_size=0.3)

In [7]:
ohe = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')

In [8]:
ct = make_column_transformer(
                            (ohe, make_column_selector(dtype_include = object)),
                            ('passthrough', make_column_selector(dtype_include =['int64','float64'])),
                             verbose_feature_names_out = False)
ct = ct.set_output(transform = 'pandas')
x_ohe = ct.fit_transform(X_train)
x_ohe

,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest,age,bmi,children
219,0.0,0.0,0.0,1.0,0.0,24,23.21,0
351,0.0,0.0,0.0,0.0,1.0,50,25.60,0
824,1.0,0.0,1.0,0.0,0.0,60,24.32,0
484,1.0,0.0,0.0,0.0,1.0,48,34.30,3
647,0.0,0.0,0.0,0.0,0.0,40,23.37,3
...,...,...,...,...,...,...,...,...
941,0.0,0.0,0.0,1.0,0.0,50,46.09,1
160,0.0,1.0,1.0,0.0,0.0,42,26.60,0
1101,1.0,0.0,0.0,0.0,1.0,53,28.60,3
1126,1.0,0.0,0.0,0.0,1.0,55,29.90,0
821,1.0,0.0,1.0,0.0,0.0,26,17.67,0

LinearRegression()

In [22]:
# One-hot-encoding on test data
X_test_transf = ct.transform(X_test)

In [14]:
lr = LinearRegression()
lr.fit(x_ohe, y_train)

y_pred = lr.predict(X_test_transf)
r2score = r2_score(y_test,y_pred)
r2score

0.7625873682287879

In [19]:
alphas = np.linspace(0.001, 10.0,20) 

lst = []

for alp in alphas:
    ridg = Ridge(alpha=alp)
    ridg.fit(x_ohe, y_train)
    y_pred = ridg.predict(X_test_transf)
    lst.append([alp,r2_score(y_test, y_pred)]) 

valsdic = pd.DataFrame(lst, columns = ['alpha','ridge r2 score'])
valsdic.sort_values('ridge r2 score',ascending = False)

        alpha  ridge r2 score
0    0.001000        0.762587
1    0.527263        0.762494
2    1.053526        0.762387
3    1.579789        0.762265
4    2.106053        0.762131
5    2.632316        0.761983
6    3.158579        0.761822
7    3.684842        0.761649
8    4.211105        0.761463
9    4.737368        0.761266
10   5.263632        0.761056
11   5.789895        0.760836
12   6.316158        0.760603
13   6.842421        0.760360
14   7.368684        0.760106
15   7.894947        0.759842
16   8.421211        0.759567
17   8.947474        0.759282
18   9.473737        0.758988
19  10.000000        0.758684

In [20]:
valsdic = pd.DataFrame(index = alphas)

lst = []
for alp in alphas:
    lasso = Lasso(alpha=alp)
    lasso.fit(x_ohe, y_train)
    y_pred = lasso.predict(X_test_transf)
    lst.append([alp,r2_score(y_test, y_pred)]) 

valsdic = pd.DataFrame(lst,columns = ['alpha','lasso r2 score'])
valsdic.sort_values('lasso r2 score',ascending = False)

        alpha  lasso r2 score
0    0.001000        0.762587
1    0.527263        0.762585
2    1.053526        0.762583
3    1.579789        0.762580
4    2.106053        0.762577
5    2.632316        0.762574
6    3.158579        0.762570
7    3.684842        0.762566
8    4.211105        0.762563
9    4.737368        0.762558
19  10.000000        0.762558
10   5.263632        0.762554
18   9.473737        0.762553
11   5.789895        0.762549
17   8.947474        0.762548
12   6.316158        0.762545
16   8.421211        0.762542
13   6.842421        0.762540
15   7.894947        0.762536
14   7.368684        0.762534

In [21]:

l1_ratios = np.linspace(0.001,1,20)
scores = []
for alp in alphas:
    for r in l1_ratios:
        elnet = ElasticNet(alpha=alp, l1_ratio = r)
        elnet.fit(x_ohe, y_train)
        y_pred = elnet.predict(X_test_transf)
        scores.append([alp,r,r2_score(y_test, y_pred)])

 

# 2. Convert the list of results into a DataFrame
df_scores = pd.DataFrame(scores, columns=['alpha', 'l1_ratio', 'r2_score'])
df_scores.sort_values('r2_score',ascending = False)

         alpha  l1_ratio  r2_score
19    0.001000  1.000000  0.762587
39    0.527263  1.000000  0.762585
59    1.053526  1.000000  0.762583
79    1.579789  1.000000  0.762580
18    0.001000  0.947421  0.762579
..         ...       ...       ...
382  10.000000  0.106158  0.164873
361   9.473737  0.053579  0.164799
360   9.473737  0.001000  0.163410
381  10.000000  0.053579  0.163404
380  10.000000  0.001000  0.162054

[400 rows x 3 columns]

In [23]:
# find out best model -> lr

#inferencing 
''' 
1. fit the best model on whole data
2. Apply it on unlabelled data
'''

' \n1. fit the best model on whole data\n2. Apply it on unlabelled data\n'

In [24]:
df = pd.read_csv('insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [26]:
x,y = df.drop(columns = ['charges']), df['charges']
 
ohe = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')
ct = make_column_transformer(
                            (ohe, make_column_selector(dtype_include = object)),
                            ('passthrough', make_column_selector(dtype_include =['int64','float64'])),
                             verbose_feature_names_out = False)
ct = ct.set_output(transform = 'pandas')
x_ohe = ct.fit_transform(x)
x_ohe

,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest,age,bmi,children
0,0.0,1.0,0.0,0.0,1.0,19,27.900,0
1,1.0,0.0,0.0,1.0,0.0,18,33.770,1
2,1.0,0.0,0.0,1.0,0.0,28,33.000,3
3,1.0,0.0,1.0,0.0,0.0,33,22.705,0
4,1.0,0.0,1.0,0.0,0.0,32,28.880,0
...,...,...,...,...,...,...,...,...
1333,1.0,0.0,1.0,0.0,0.0,50,30.970,3
1334,0.0,0.0,0.0,0.0,0.0,18,31.920,0
1335,0.0,0.0,0.0,1.0,0.0,18,36.850,0
1336,0.0,0.0,0.0,0.0,1.0,21,25.800,0
1337,0.0,1.0,1.0,0.0,0.0,61,29.070,0

In [31]:
lr = LinearRegression()
lr.fit(x_ohe, y)

testdf = pd.read_csv('tst_insure.csv')
testenc = ct.transform(testdf)

pred = lr.predict(testenc)  
pred

print('predictions => ')
testdf['predicted charges'] = pred
testdf

predictions =>

    age     sex     bmi  children smoker     region  predicted charges
0    19  female  27.900         0    yes  southwest       25293.713028
1    18    male  33.770         1     no  southeast        3448.602834
2    28    male  33.000         3     no  southeast        6706.988491
3    33    male  22.705         0     no  northwest        3754.830163
4    37  female  23.370         2     no  northwest        6090.134669
..  ...     ...     ...       ...    ...        ...                ...
83   60    male  24.320         1     no  northwest       11713.249654
84   51  female  36.670         2     no  northwest       14197.396538
85   58  female  33.440         0     no  northwest       13948.795060
86   36    male  34.430         2     no  southeast        8771.385405
87   20  female  31.460         0     no  southeast        2834.592476

[88 rows x 7 columns]