In [12]:
import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer

import os
os.chdir(r'E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

In [4]:
job = pd.read_csv('JobSalary2.csv', index_col = 0)
job

      Computer  Marketing  Engineer
S_No
1         84.0       55.0        75
2         90.0       53.0        70
3         63.0        NaN        88
4          NaN       50.0        77
5         63.0       41.0        89
6         75.0       54.0        85
7          NaN       51.0        96
8         77.0       64.0       105

In [9]:
job.mean()

Computer     75.333333
Marketing    52.571429
Engineer     85.625000
dtype: float64

### Mean Imputation

In [7]:
mu = dict(job.mean())
job.fillna(mu)

       Computer  Marketing  Engineer
S_No
1     84.000000  55.000000        75
2     90.000000  53.000000        70
3     63.000000  52.571429        88
4     75.333333  50.000000        77
5     63.000000  41.000000        89
6     75.000000  54.000000        85
7     75.333333  51.000000        96
8     77.000000  64.000000       105

### Median Imputation

In [8]:
mu = dict(job.median())
job.fillna(mu)

      Computer  Marketing  Engineer
S_No
1         84.0       55.0        75
2         90.0       53.0        70
3         63.0       53.0        88
4         76.0       50.0        77
5         63.0       41.0        89
6         75.0       54.0        85
7         76.0       51.0        96
8         77.0       64.0       105

In [13]:
# SImpleImputer

In [18]:
imputer  = SimpleImputer(strategy='mean').set_output(transform='pandas')
imputer.fit(job) # calculates the statistics
print(imputer.statistics_)

imputer.transform(job) # fills the na with stat values

[75.33333333 52.57142857 85.625     ]

       Computer  Marketing  Engineer
S_No
1     84.000000  55.000000      75.0
2     90.000000  53.000000      70.0
3     63.000000  52.571429      88.0
4     75.333333  50.000000      77.0
5     63.000000  41.000000      89.0
6     75.000000  54.000000      85.0
7     75.333333  51.000000      96.0
8     77.000000  64.000000     105.0