In [31]:
import os
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report, root_mean_squared_error , mean_absolute_error , mean_squared_error
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay , roc_curve, RocCurveDisplay, roc_auc_score 


from sklearn.linear_model import LinearRegression, Ridge, Lasso 
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor 


from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import   GradientBoostingRegressor, StackingRegressor
from catboost import CatBoostRegressor
import lightgbm as lgb

from sklearn.preprocessing import OneHotEncoder , StandardScaler, LabelEncoder
from sklearn.compose import make_column_transformer , make_column_selector
 

from sklearn.model_selection import train_test_split , KFold ,cross_val_score, cross_val_predict
from tqdm import tqdm
from sklearn.pipeline import Pipeline



import warnings
warnings.filterwarnings("ignore")

os.chdir(r"C:\Users\RAJESH\Desktop\ss\Datasets")

In [32]:
pizza = pd.read_csv('pizza.csv')
pizza

    Promote  Sales
0        23    554
1        56   1339
2        34    815
3        25    609
4        67   1600
5        82   2000
6        46   1000
7        14    300
8         6    150
9        47   1150
10       52   1200
11       88   2000
12       71   1750
13       78   2000
14       66   1500
15       44   1000
16       68   1600
17       90   2000
18       22    550

In [33]:
X,y = pizza[['Promote']] , pizza['Sales']

lr = LinearRegression()
# kfold = KFold.split(pizza,X)
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

In [34]:
pizza

    Promote  Sales
0        23    554
1        56   1339
2        34    815
3        25    609
4        67   1600
5        82   2000
6        46   1000
7        14    300
8         6    150
9        47   1150
10       52   1200
11       88   2000
12       71   1750
13       78   2000
14       66   1500
15       44   1000
16       68   1600
17       90   2000
18       22    550

In [35]:
cross_val_score(lr,X , y, cv = kfold)

array([0.99257911, 0.98462674, 0.96980592, 0.99362478, 0.87675568])

In [36]:
 cross_val_predict(lr,X , y, cv = kfold)

array([ 542.6878013 , 1321.28919963,  803.96975084,  592.98723009,
       1571.43472514, 1934.73272559, 1097.30455915,  337.9866927 ,
        154.10985439, 1115.78824921, 1238.58003158, 2076.29661619,
       1664.52514269, 1817.2241202 , 1568.22280058, 1043.8301342 ,
       1586.23602773, 2147.18789766,  524.16752779])

In [ ]:
# for classification prob use stratifiedkfold