In [271]:
import numpy as np
import pandas as pd

In [272]:
data = {
    'name': ['Zoya Akhtar', 'Rahul Sharma', 'Emily Watson', 'Karan Patel','Karan Patel'],
    'email': ['zoya@example.com', 'rahul@example.com', 'emily@example.com', 'karan@example.com','df'],
    'salary': [92000, 78000, 105000, 64000,550000]
}
df = pd.DataFrame(data=data)
df

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000

In [273]:
df['Bonus'] = df['salary'] * 0.15
df

           name              email  salary    Bonus
0   Zoya Akhtar   zoya@example.com   92000  13800.0
1  Rahul Sharma  rahul@example.com   78000  11700.0
2  Emily Watson  emily@example.com  105000  15750.0
3   Karan Patel  karan@example.com   64000   9600.0
4   Karan Patel                 df  550000  82500.0

In [274]:
df[['fname','lname']] = df['name'].str.split(' ',expand=True)
df

           name              email  salary    Bonus  fname   lname
0   Zoya Akhtar   zoya@example.com   92000  13800.0   Zoya  Akhtar
1  Rahul Sharma  rahul@example.com   78000  11700.0  Rahul  Sharma
2  Emily Watson  emily@example.com  105000  15750.0  Emily  Watson
3   Karan Patel  karan@example.com   64000   9600.0  Karan   Patel
4   Karan Patel                 df  550000  82500.0  Karan   Patel

In [275]:
df['Age'] = [35,32,40,30,40]
df

           name              email  salary    Bonus  fname   lname  Age
0   Zoya Akhtar   zoya@example.com   92000  13800.0   Zoya  Akhtar   35
1  Rahul Sharma  rahul@example.com   78000  11700.0  Rahul  Sharma   32
2  Emily Watson  emily@example.com  105000  15750.0  Emily  Watson   40
3   Karan Patel  karan@example.com   64000   9600.0  Karan   Patel   30
4   Karan Patel                 df  550000  82500.0  Karan   Patel   40

In [276]:
df['BloodGrp'] = ['B','O','o','A','a']
# df.insert(2,'BloodGrp',['B','O','o','A','a'])  # 2nd column
df

,name,email,salary,Bonus,fname,lname,Age,BloodGrp
0,Zoya Akhtar,zoya@example.com,92000,13800.0,Zoya,Akhtar,35,B
1,Rahul Sharma,rahul@example.com,78000,11700.0,Rahul,Sharma,32,O
2,Emily Watson,emily@example.com,105000,15750.0,Emily,Watson,40,o
3,Karan Patel,karan@example.com,64000,9600.0,Karan,Patel,30,A
4,Karan Patel,df,550000,82500.0,Karan,Patel,40,a

In [277]:
# df.drop(columns=['name','BloodGrp'], inplace=True)
# df

df2 = df.drop(columns=['name','BloodGrp'])
df2

               email  salary    Bonus  fname   lname  Age
0   zoya@example.com   92000  13800.0   Zoya  Akhtar   35
1  rahul@example.com   78000  11700.0  Rahul  Sharma   32
2  emily@example.com  105000  15750.0  Emily  Watson   40
3  karan@example.com   64000   9600.0  Karan   Patel   30
4                 df  550000  82500.0  Karan   Patel   40

In [278]:
data = {
    'name': ['Zoya Akhtar', 'Rahul Sharma', 'Emily Watson', 'Karan Patel','Karan Patel'],
    'email': ['zoya@example.com', 'rahul@example.com', 'emily@example.com', 'karan@example.com','df'],
    'salary': [92000, 78000, 105000, 64000,550000]
}
df = pd.DataFrame(data=data)
df

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000

In [279]:
row_data = {
    'name':'Rudra nav', 'email':'rudra32@mail.com','salary':90000
}
df = pd.concat([df,pd.DataFrame([row_data])], ignore_index=True)

In [280]:
df

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000
5     Rudra nav   rudra32@mail.com   90000

In [281]:
data = {
    'name':['ram','jay','Zoya Akhtar'],
    'email':['sd','fd','ff'],
    'salary': [12,34,67]
}
df =pd.concat([df,pd.DataFrame(data=data)], ignore_index=True)
df

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000
5     Rudra nav   rudra32@mail.com   90000
6           ram                 sd      12
7           jay                 fd      34
8   Zoya Akhtar                 ff      67

In [282]:
filt = df.duplicated(subset=['salary'])

In [283]:
df[filt]

Empty DataFrame
Columns: [name, email, salary]
Index: []

In [284]:
df[~filt]   # not ~

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000
5     Rudra nav   rudra32@mail.com   90000
6           ram                 sd      12
7           jay                 fd      34
8   Zoya Akhtar                 ff      67

In [285]:
df.drop_duplicates(subset=['name'])

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
5     Rudra nav   rudra32@mail.com   90000
6           ram                 sd      12
7           jay                 fd      34

In [286]:
df.drop_duplicates(keep='last',inplace=True)

In [287]:
df

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000
5     Rudra nav   rudra32@mail.com   90000
6           ram                 sd      12
7           jay                 fd      34
8   Zoya Akhtar                 ff      67

In [288]:
df.to_csv('cleans_data.csv')

In [289]:
data = {
    'name': ['Zoya Akhtar', 'Rahul Sharma', 'Emily Watson', 'Karan Patel','Karan Patel'],
    'email': ['zoya@example.com', 'rahul@example.com', 'emily@example.com', 'karan@example.com','df'],
    'salary': [92000, 78000, 105000, 64000,550000],
    'bonus': [12,43,546,34,34],
    'gender' : ['m','f','m','f','m']
}
df = pd.DataFrame(data=data)
df

           name              email  salary  bonus gender
0   Zoya Akhtar   zoya@example.com   92000     12      m
1  Rahul Sharma  rahul@example.com   78000     43      f
2  Emily Watson  emily@example.com  105000    546      m
3   Karan Patel  karan@example.com   64000     34      f
4   Karan Patel                 df  550000     34      m

In [290]:
df.columns = [s.upper() for s in df.columns]

In [291]:
df

           NAME              EMAIL  SALARY  BONUS GENDER
0   Zoya Akhtar   zoya@example.com   92000     12      m
1  Rahul Sharma  rahul@example.com   78000     43      f
2  Emily Watson  emily@example.com  105000    546      m
3   Karan Patel  karan@example.com   64000     34      f
4   Karan Patel                 df  550000     34      m

In [292]:
df.columns = list(map(lambda s: s.title(), df.columns))

In [293]:
df

           Name              Email  Salary  Bonus Gender
0   Zoya Akhtar   zoya@example.com   92000     12      m
1  Rahul Sharma  rahul@example.com   78000     43      f
2  Emily Watson  emily@example.com  105000    546      m
3   Karan Patel  karan@example.com   64000     34      f
4   Karan Patel                 df  550000     34      m

In [294]:
df.rename(columns = {'Email':'EmailId'},inplace=True)
df

           Name            EmailId  Salary  Bonus Gender
0   Zoya Akhtar   zoya@example.com   92000     12      m
1  Rahul Sharma  rahul@example.com   78000     43      f
2  Emily Watson  emily@example.com  105000    546      m
3   Karan Patel  karan@example.com   64000     34      f
4   Karan Patel                 df  550000     34      m

In [295]:
df.loc[2,'EmailId'] = ['gfhfgh']

In [296]:
df

           Name            EmailId  Salary  Bonus Gender
0   Zoya Akhtar   zoya@example.com   92000     12      m
1  Rahul Sharma  rahul@example.com   78000     43      f
2  Emily Watson             gfhfgh  105000    546      m
3   Karan Patel  karan@example.com   64000     34      f
4   Karan Patel                 df  550000     34      m

In [297]:
df.apply(len)

Name       5
EmailId    5
Salary     5
Bonus      5
Gender     5
dtype: int64

In [298]:
df.apply(min)

Name       Emily Watson
EmailId              df
Salary            64000
Bonus                12
Gender                f
dtype: object

In [299]:
df['Difference'] = df.apply(lambda row: row['Salary'] - row['Bonus'], axis=1)

In [300]:
x = df.apply(lambda col: min(col), axis=0)
print(type(x))
print(x)

<class 'pandas.Series'>
Name          Emily Watson
EmailId                 df
Salary               64000
Bonus                   12
Gender                   f
Difference           63966
dtype: object

In [301]:
df

           Name            EmailId  Salary  Bonus Gender  Difference
0   Zoya Akhtar   zoya@example.com   92000     12      m       91988
1  Rahul Sharma  rahul@example.com   78000     43      f       77957
2  Emily Watson             gfhfgh  105000    546      m      104454
3   Karan Patel  karan@example.com   64000     34      f       63966
4   Karan Patel                 df  550000     34      m      549966

In [302]:
df['Gender'] = df['Gender'].map({'m':'Male', 'f':'Female'})# if invalid value then assigned with NaN

In [303]:
df

           Name            EmailId  Salary  Bonus  Gender  Difference
0   Zoya Akhtar   zoya@example.com   92000     12    Male       91988
1  Rahul Sharma  rahul@example.com   78000     43  Female       77957
2  Emily Watson             gfhfgh  105000    546    Male      104454
3   Karan Patel  karan@example.com   64000     34  Female       63966
4   Karan Patel                 df  550000     34    Male      549966

In [304]:
df = df.replace({'Zoya Akhtar':'ram akhtar','zoya@example.com':'abc@12'})

In [305]:
df

           Name            EmailId  Salary  Bonus  Gender  Difference
0    ram akhtar             abc@12   92000     12    Male       91988
1  Rahul Sharma  rahul@example.com   78000     43  Female       77957
2  Emily Watson             gfhfgh  105000    546    Male      104454
3   Karan Patel  karan@example.com   64000     34  Female       63966
4   Karan Patel                 df  550000     34    Male      549966

In [306]:
df['Name'] = df['Name'].map({'ram akhtar':'Ram Akhtar'})
df

         Name            EmailId  Salary  Bonus  Gender  Difference
0  Ram Akhtar             abc@12   92000     12    Male       91988
1         NaN  rahul@example.com   78000     43  Female       77957
2         NaN             gfhfgh  105000    546    Male      104454
3         NaN  karan@example.com   64000     34  Female       63966
4         NaN                 df  550000     34    Male      549966