In [41]:
import numpy as np
import pandas as pd

In [42]:
data = {
    'name': ['Zoya Akhtar', 'Rahul Sharma', 'Emily Watson', 'Karan Patel','Karan Patel'],
    'email': ['zoya@example.com', 'rahul@example.com', 'emily@example.com', 'karan@example.com','df'],
    'salary': [92000, 78000, 105000, 64000,550000]
}
df = pd.DataFrame(data=data)
df

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000

In [43]:
df['bonus'] = df['salary'] * 0.15
df

           name              email  salary    bonus
0   Zoya Akhtar   zoya@example.com   92000  13800.0
1  Rahul Sharma  rahul@example.com   78000  11700.0
2  Emily Watson  emily@example.com  105000  15750.0
3   Karan Patel  karan@example.com   64000   9600.0
4   Karan Patel                 df  550000  82500.0

In [44]:
df[['firt_name','last_name']] = df['name'].str.split(' ',expand=True)
df

           name              email  salary    bonus firt_name last_name
0   Zoya Akhtar   zoya@example.com   92000  13800.0      Zoya    Akhtar
1  Rahul Sharma  rahul@example.com   78000  11700.0     Rahul    Sharma
2  Emily Watson  emily@example.com  105000  15750.0     Emily    Watson
3   Karan Patel  karan@example.com   64000   9600.0     Karan     Patel
4   Karan Patel                 df  550000  82500.0     Karan     Patel

In [45]:
df['Age'] = [23,24,25,27,28]
df

           name              email  salary    bonus firt_name last_name  Age
0   Zoya Akhtar   zoya@example.com   92000  13800.0      Zoya    Akhtar   23
1  Rahul Sharma  rahul@example.com   78000  11700.0     Rahul    Sharma   24
2  Emily Watson  emily@example.com  105000  15750.0     Emily    Watson   25
3   Karan Patel  karan@example.com   64000   9600.0     Karan     Patel   27
4   Karan Patel                 df  550000  82500.0     Karan     Patel   28

In [46]:
df.insert(2,'Bloodgrp', ['B','A','O','AB','A'])
df

,name,email,Bloodgrp,salary,bonus,firt_name,last_name,Age
0,Zoya Akhtar,zoya@example.com,B,92000,13800.0,Zoya,Akhtar,23
1,Rahul Sharma,rahul@example.com,A,78000,11700.0,Rahul,Sharma,24
2,Emily Watson,emily@example.com,O,105000,15750.0,Emily,Watson,25
3,Karan Patel,karan@example.com,AB,64000,9600.0,Karan,Patel,27
4,Karan Patel,df,A,550000,82500.0,Karan,Patel,28

In [47]:
df.drop(columns=['name','bonus'], inplace=True)
df

               email Bloodgrp  salary firt_name last_name  Age
0   zoya@example.com        B   92000      Zoya    Akhtar   23
1  rahul@example.com        A   78000     Rahul    Sharma   24
2  emily@example.com        O  105000     Emily    Watson   25
3  karan@example.com       AB   64000     Karan     Patel   27
4                 df        A  550000     Karan     Patel   28

In [48]:
data = {
    'name': ['Zoya Akhtar', 'Rahul Sharma', 'Emily Watson', 'Karan Patel','Karan Patel'],
    'email': ['zoya@example.com', 'rahul@example.com', 'emily@example.com', 'karan@example.com','df'],
    'salary': [92000, 78000, 105000, 64000,550000]
}
df = pd.DataFrame(data=data)
df

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000

In [49]:
row_data = {
    'name': 'Esha',
    'email': 'esha@email.com',
    'salary': 23000
}
df = pd.concat([df, pd.DataFrame([row_data])])
df

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000
0          Esha     esha@email.com   23000

In [50]:
row_data = {
    'name': ['Ashis','Abhinav'],
    'email': ['ashis@email.com','abhinav@email.com'],
    'salary': [25000,25000]
}
df = pd.concat([df,pd.DataFrame(row_data)])
df

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000
0          Esha     esha@email.com   23000
0         Ashis    ashis@email.com   25000
1       Abhinav  abhinav@email.com   25000

In [51]:
filt = df.duplicated(subset=['salary'])
df[filt]

      name              email  salary
1  Abhinav  abhinav@email.com   25000

In [52]:
df[~filt]

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000
0          Esha     esha@email.com   23000
0         Ashis    ashis@email.com   25000