In [ ]:
import numpy as np

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('file_name.csv')
df

,title,price,availability,url
0,A Light in the ...,£51.77,In stock,catalogue/a-light-in-the-attic_1000/index.html
1,Tipping the Velvet,£53.74,In stock,catalogue/tipping-the-velvet_999/index.html
2,Soumission,£50.10,In stock,catalogue/soumission_998/index.html
3,Sharp Objects,£47.82,In stock,catalogue/sharp-objects_997/index.html
4,Sapiens: A Brief History ...,£54.23,In stock,catalogue/sapiens-a-brief-history-of-humankind...
...,...,...,...,...
995,Alice in Wonderland (Alice's ...,£55.53,In stock,alice-in-wonderland-alices-adventures-in-wonde...
996,"Ajin: Demi-Human, Volume 1 ...",£57.06,In stock,ajin-demi-human-volume-1-ajin-demi-human-1_4/i...
997,A Spy's Devotion (The ...,£16.97,In stock,a-spys-devotion-the-regency-spies-of-london-1_...
998,1st to Die (Women's ...,£53.98,In stock,1st-to-die-womens-murder-club-1_2/index.html
999,"1,000 Places to See ...",£26.08,In stock,1000-places-to-see-before-you-die_1/index.html

In [4]:
type(df['price'][0])

str

In [14]:
df['priced'] = df['price'].str[1:]
df.dropna()
df['priced'] = df['priced'].astype(float)

In [15]:
df

,title,price,availability,url,priced
0,A Light in the ...,£51.77,In stock,catalogue/a-light-in-the-attic_1000/index.html,51.77
1,Tipping the Velvet,£53.74,In stock,catalogue/tipping-the-velvet_999/index.html,53.74
2,Soumission,£50.10,In stock,catalogue/soumission_998/index.html,50.10
3,Sharp Objects,£47.82,In stock,catalogue/sharp-objects_997/index.html,47.82
4,Sapiens: A Brief History ...,£54.23,In stock,catalogue/sapiens-a-brief-history-of-humankind...,54.23
...,...,...,...,...,...
995,Alice in Wonderland (Alice's ...,£55.53,In stock,alice-in-wonderland-alices-adventures-in-wonde...,55.53
996,"Ajin: Demi-Human, Volume 1 ...",£57.06,In stock,ajin-demi-human-volume-1-ajin-demi-human-1_4/i...,57.06
997,A Spy's Devotion (The ...,£16.97,In stock,a-spys-devotion-the-regency-spies-of-london-1_...,16.97
998,1st to Die (Women's ...,£53.98,In stock,1st-to-die-womens-murder-club-1_2/index.html,53.98
999,"1,000 Places to See ...",£26.08,In stock,1000-places-to-see-before-you-die_1/index.html,26.08

In [ ]:
df[df.where(df['priced'] > 50)

,title,price,availability,url,priced
0,A Light in the ...,£51.77,In stock,catalogue/a-light-in-the-attic_1000/index.html,51.77
1,Tipping the Velvet,£53.74,In stock,catalogue/tipping-the-velvet_999/index.html,53.74
2,Soumission,£50.10,In stock,catalogue/soumission_998/index.html,50.10
3,NaN,NaN,NaN,NaN,NaN
4,Sapiens: A Brief History ...,£54.23,In stock,catalogue/sapiens-a-brief-history-of-humankind...,54.23
...,...,...,...,...,...
995,Alice in Wonderland (Alice's ...,£55.53,In stock,alice-in-wonderland-alices-adventures-in-wonde...,55.53
996,"Ajin: Demi-Human, Volume 1 ...",£57.06,In stock,ajin-demi-human-volume-1-ajin-demi-human-1_4/i...,57.06
997,NaN,NaN,NaN,NaN,NaN
998,1st to Die (Women's ...,£53.98,In stock,1st-to-die-womens-murder-club-1_2/index.html,53.98
999,NaN,NaN,NaN,NaN,NaN