In [3]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules



import os 
os.chdir(r'E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

import warnings
warnings.filterwarnings("ignore")

In [4]:
fp_df = pd.read_csv('Cosmetics.csv',index_col=0)
fp_df = fp_df.astype(bool)
fp_df

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
Trans.,,,,,,,,,,,,,,
1,False,True,True,True,True,False,True,True,True,False,False,False,False,True
2,False,False,True,False,True,False,True,True,False,False,True,True,False,False
3,False,True,False,False,True,True,True,True,True,True,True,True,True,False
4,False,False,True,True,True,False,True,False,False,False,True,False,False,True
5,False,True,False,False,True,False,True,True,True,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,True,True,False,False
998,False,True,True,True,True,False,False,True,False,False,True,False,True,True
999,True,True,False,False,True,False,False,False,True,True,False,False,True,True
1000,False,False,False,False,True,False,True,True,False,True,False,False,False,True

In [5]:
itemsets = apriori(fp_df, min_support=0.2, use_colnames=True)
itemsets

    support                  itemsets
0     0.363                   (Blush)
1     0.280             (Nail Polish)
2     0.442               (Concealer)
3     0.279                 (Bronzer)
4     0.234               (Lip liner)
5     0.357                 (Mascara)
6     0.381              (Eye shadow)
7     0.536              (Foundation)
8     0.490               (Lip Gloss)
9     0.322                (Lipstick)
10    0.457                (Eyeliner)
11    0.220        (Blush, Concealer)
12    0.204      (Mascara, Concealer)
13    0.201   (Eye shadow, Concealer)
14    0.231   (Foundation, Concealer)
15    0.218    (Lip Gloss, Concealer)
16    0.297     (Eyeliner, Concealer)
17    0.321     (Mascara, Eye shadow)
18    0.211  (Foundation, Eye shadow)
19    0.201   (Lip Gloss, Eye shadow)
20    0.356   (Foundation, Lip Gloss)
21    0.238    (Foundation, Eyeliner)
22    0.227     (Eyeliner, Lip Gloss)

In [9]:
rules = association_rules(itemsets , metric='confidence' , min_threshold=0.5)
rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift',]]
rules.sort_values(by=['confidence','lift','support'], ascending=False)

     antecedents   consequents  support  confidence      lift
6      (Mascara)  (Eye shadow)    0.321    0.899160  2.359999
7   (Eye shadow)     (Mascara)    0.321    0.842520  2.359999
11   (Lip Gloss)  (Foundation)    0.356    0.726531  1.355468
5    (Concealer)    (Eyeliner)    0.297    0.671946  1.470341
10  (Foundation)   (Lip Gloss)    0.356    0.664179  1.355468
4     (Eyeliner)   (Concealer)    0.297    0.649891  1.470341
0        (Blush)   (Concealer)    0.220    0.606061  1.371178
1      (Mascara)   (Concealer)    0.204    0.571429  1.292825
8   (Eye shadow)  (Foundation)    0.211    0.553806  1.033220
2   (Eye shadow)   (Concealer)    0.201    0.527559  1.193573
9   (Eye shadow)   (Lip Gloss)    0.201    0.527559  1.076651
3    (Concealer)  (Foundation)    0.231    0.522624  0.975046
12    (Eyeliner)  (Foundation)    0.238    0.520788  0.971619

In [10]:
relv_rules= rules[rules['lift']>1]
relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

     antecedents   consequents  support  confidence      lift
6      (Mascara)  (Eye shadow)    0.321    0.899160  2.359999
7   (Eye shadow)     (Mascara)    0.321    0.842520  2.359999
11   (Lip Gloss)  (Foundation)    0.356    0.726531  1.355468
5    (Concealer)    (Eyeliner)    0.297    0.671946  1.470341
10  (Foundation)   (Lip Gloss)    0.356    0.664179  1.355468
4     (Eyeliner)   (Concealer)    0.297    0.649891  1.470341
0        (Blush)   (Concealer)    0.220    0.606061  1.371178
1      (Mascara)   (Concealer)    0.204    0.571429  1.292825
8   (Eye shadow)  (Foundation)    0.211    0.553806  1.033220
2   (Eye shadow)   (Concealer)    0.201    0.527559  1.193573
9   (Eye shadow)   (Lip Gloss)    0.201    0.527559  1.076651

# Widgets

In [11]:
from ipywidgets import interact
import ipywidgets as widgets

'''
ipywidgets (IPython Widgets) is a Python library that lets you build interactive GUI 
controls—like sliders, dropdowns, buttons, and text boxes—directly inside your Jupyter Notebook.
'''

In [14]:
def gen_rules(min_support , minconfidence):
    itemsets = apriori(fp_df, min_support=min_support, use_colnames=True)
    rules = association_rules(itemsets , metric='confidence' , min_threshold=minconfidence)
    rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift',]]
    relv_rules= rules[rules['lift']>1]
    return relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

In [26]:
interact(
    gen_rules , 
    min_support = widgets.FloatSlider(
        value = 0.2 , min = 0.01, max = 1 , step = 0.01 , description = 'Min Support:'
    ),
    minconfidence = widgets.FloatSlider(
        value = 0.2 , min = 0.01, max = 0.5 , step = 0.01, description = 'Min Confidence:'
    )
)

interactive(children=(FloatSlider(value=0.2, description='Min Support:', max=1.0, min=0.01, step=0.01), FloatS…

In [18]:
widgets.BoundedIntText(
    value=7,
    min=0,
    max=10,
    step=1,
    description='Text:',
    disabled=False
)

BoundedIntText(value=7, description='Text:', max=10)