In [16]:
import pandas as pd

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder


import os 
os.chdir(r'E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')
import warnings
warnings.filterwarnings("ignore")

In [17]:

groceries = []
with open('DataSetA.csv',"r") as f:groceries = f.read()
groceries = groceries.split("\n")

groceries_list = []
for i in groceries:
    groceries_list.append(i.split(","))
# groceries
# groceries_list

In [19]:
te = TransactionEncoder()
te_ary = te.fit(groceries_list).transform(groceries_list)
fp_df = pd.DataFrame(te_ary , columns=te.columns_)
fp_df = fp_df.iloc[: , 1:]
fp_df

,Bread,Butter,Cheese,Coffee Powder,Ghee,Lassi,Milk,Panner,Sugar,Sweet,Tea Powder,Yougurt
0,False,True,True,True,True,True,False,False,False,False,False,True
1,False,False,False,True,True,False,False,False,False,False,False,False
2,False,True,True,False,False,True,False,False,False,False,True,False
3,True,True,True,True,False,False,False,True,False,False,True,False
4,False,True,True,True,False,False,False,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
12522,True,False,True,True,False,False,False,False,True,False,False,False
12523,True,False,True,False,False,False,True,False,False,False,False,True
12524,True,False,True,False,True,False,False,False,True,False,False,True
12525,True,False,False,False,False,False,False,True,False,False,False,True
12526,False,False,False,False,False,False,False,False,False,False,False,False

In [20]:
itemsets = apriori(fp_df, min_support=0.07, use_colnames=True)
itemsets

      support                       itemsets
0    0.437774                        (Bread)
1    0.437535                       (Butter)
2    0.437136                       (Cheese)
3    0.439770                (Coffee Powder)
4    0.439850                         (Ghee)
..        ...                            ...
293  0.091243  (Panner, Yougurt, Tea Powder)
294  0.094995     (Sweet, Tea Powder, Sugar)
295  0.094596        (Sweet, Yougurt, Sugar)
296  0.094915   (Yougurt, Tea Powder, Sugar)
297  0.092440   (Sweet, Yougurt, Tea Powder)

[298 rows x 2 columns]

In [21]:
rules = association_rules(itemsets , metric='confidence' , min_threshold=0.2)
rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift',]]
rules.sort_values(by=['confidence','lift','support'], ascending=False)

,antecedents,consequents,support,confidence,lift
1274,"(Panner, Lassi)",(Sweet),0.100982,0.506608,1.157446
1272,"(Sweet, Panner)",(Lassi),0.100982,0.504990,1.164582
695,"(Sweet, Sugar)",(Butter),0.099705,0.500601,1.144140
624,"(Butter, Lassi)",(Sweet),0.099545,0.498601,1.139152
1310,"(Lassi, Tea Powder)",(Sweet),0.097070,0.498565,1.139071
...,...,...,...,...,...
1065,(Coffee Powder),"(Panner, Tea Powder)",0.088688,0.201670,1.048701
770,(Cheese),"(Coffee Powder, Tea Powder)",0.088130,0.201607,1.030408
1342,(Milk),"(Panner, Tea Powder)",0.088848,0.201412,1.047357
845,(Cheese),"(Lassi, Tea Powder)",0.087810,0.200877,1.031726
769,(Coffee Powder),"(Cheese, Tea Powder)",0.088130,0.200399,1.049938

In [22]:
relv_rules= rules[rules['lift']>1]
relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

,antecedents,consequents,support,confidence,lift
1274,"(Panner, Lassi)",(Sweet),0.100982,0.506608,1.157446
1272,"(Sweet, Panner)",(Lassi),0.100982,0.504990,1.164582
695,"(Sweet, Sugar)",(Butter),0.099705,0.500601,1.144140
624,"(Butter, Lassi)",(Sweet),0.099545,0.498601,1.139152
1310,"(Lassi, Tea Powder)",(Sweet),0.097070,0.498565,1.139071
...,...,...,...,...,...
1065,(Coffee Powder),"(Panner, Tea Powder)",0.088688,0.201670,1.048701
770,(Cheese),"(Coffee Powder, Tea Powder)",0.088130,0.201607,1.030408
1342,(Milk),"(Panner, Tea Powder)",0.088848,0.201412,1.047357
845,(Cheese),"(Lassi, Tea Powder)",0.087810,0.200877,1.031726
769,(Coffee Powder),"(Cheese, Tea Powder)",0.088130,0.200399,1.049938

In [23]:
from ipywidgets import interact
import ipywidgets as widgets

In [24]:
def gen_rules(min_support , minconfidence):
    itemsets = apriori(fp_df, min_support=min_support, use_colnames=True)
    rules = association_rules(itemsets , metric='confidence' , min_threshold=minconfidence)
    rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift',]]
    relv_rules= rules[rules['lift']>1]
    return relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

In [25]:
interact(
    gen_rules , 
    min_support = widgets.FloatSlider(
        value = 0.2 , min = 0.01, max = 0.4 , step = 0.01 , description = 'Min Support:'
    ),
    minconfidence = widgets.FloatSlider(
        value = 0.2 , min = 0.01, max = 0.5 , step = 0.01, description = 'Min Confidence:'
    )
)

interactive(children=(FloatSlider(value=0.2, description='Min Support:', max=0.4, min=0.01, step=0.01), FloatS…