In [1]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder
from sklearn.preprocessing import OneHotEncoder

import os 
os.chdir(r'E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\human-resources-analytics')
import warnings
warnings.filterwarnings("ignore")

In [10]:
hr = pd.read_csv('HR_comma_sep.csv')
hr

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14990,0.40,0.57,2,151,3,0,1,0,support,low
14991,0.37,0.48,2,160,3,0,1,0,support,low
14992,0.37,0.53,2,143,3,0,1,0,support,low
14993,0.11,0.96,6,280,4,0,1,0,support,low
14994,0.37,0.52,2,158,3,0,1,0,support,low

In [11]:
hr.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project             int64
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
left                       int64
promotion_last_5years      int64
Department                object
salary                    object
dtype: object

In [12]:
hr.describe()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
count,14995.000000,14995.000000,14995.000000,14995.000000,14995.000000,14995.000000,14995.000000,14995.000000
mean,0.612890,0.716108,3.803001,201.050150,3.498166,0.144648,0.237879,0.021274
std,0.248615,0.171166,1.232266,49.943356,1.460262,0.351758,0.425799,0.144300
min,0.090000,0.360000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000
25%,0.440000,0.560000,3.000000,156.000000,3.000000,0.000000,0.000000,0.000000
50%,0.640000,0.720000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000
75%,0.820000,0.870000,5.000000,245.000000,4.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000

In [13]:
def bin_col(input, b):
    binned = pd.cut(input , bins=b)
    return binned

In [14]:
hr['satisfaction'] = bin_col(hr['satisfaction_level'], 5)
hr['evaluation'] = bin_col(hr['last_evaluation'], 5)
hr['avg_hours'] = bin_col(hr['average_montly_hours'], 5)
hr['project'] = bin_col(hr['number_project'], 3)
hr['yrs_in_comp'] = bin_col(hr['time_spend_company'], 3)
hr.drop(['satisfaction_level',	'last_evaluation',	'number_project',	'average_montly_hours',	'time_spend_company'],axis=1, inplace=True)

In [15]:
hr

,Work_accident,left,promotion_last_5years,Department,salary,satisfaction,evaluation,avg_hours,project,yrs_in_comp
0,0,1,0,sales,low,"(0.272, 0.454]","(0.488, 0.616]","(138.8, 181.6]","(1.995, 3.667]","(1.992, 4.667]"
1,0,1,0,sales,medium,"(0.636, 0.818]","(0.744, 0.872]","(224.4, 267.2]","(3.667, 5.333]","(4.667, 7.333]"
2,0,1,0,sales,low,"(0.0891, 0.272]","(0.744, 0.872]","(224.4, 267.2]","(5.333, 7.0]","(1.992, 4.667]"
3,0,1,0,sales,low,"(0.818, 1.0]","(0.744, 0.872]","(224.4, 267.2]","(3.667, 5.333]","(4.667, 7.333]"
4,0,1,0,sales,low,"(0.818, 1.0]","(0.872, 1.0]","(181.6, 224.4]","(3.667, 5.333]","(4.667, 7.333]"
...,...,...,...,...,...,...,...,...,...,...
14990,0,1,0,support,low,"(0.272, 0.454]","(0.488, 0.616]","(138.8, 181.6]","(1.995, 3.667]","(1.992, 4.667]"
14991,0,1,0,support,low,"(0.272, 0.454]","(0.359, 0.488]","(138.8, 181.6]","(1.995, 3.667]","(1.992, 4.667]"
14992,0,1,0,support,low,"(0.272, 0.454]","(0.488, 0.616]","(138.8, 181.6]","(1.995, 3.667]","(1.992, 4.667]"
14993,0,1,0,support,low,"(0.0891, 0.272]","(0.872, 1.0]","(267.2, 310.0]","(5.333, 7.0]","(1.992, 4.667]"
14994,0,1,0,support,low,"(0.272, 0.454]","(0.488, 0.616]","(138.8, 181.6]","(1.995, 3.667]","(1.992, 4.667]"

In [16]:
ohc = OneHotEncoder(sparse_output=False, dtype=np.bool_).set_output(transform='pandas')
hr_trans = ohc.fit_transform(hr)
hr_trans

,Work_accident_0,Work_accident_1,left_0,left_1,promotion_last_5years_0,promotion_last_5years_1,Department_IT,Department_RandD,Department_accounting,Department_hr,...,"avg_hours_(138.8, 181.6]","avg_hours_(181.6, 224.4]","avg_hours_(224.4, 267.2]","avg_hours_(267.2, 310.0]","project_(1.995, 3.667]","project_(3.667, 5.333]","project_(5.333, 7.0]","yrs_in_comp_(1.992, 4.667]","yrs_in_comp_(4.667, 7.333]","yrs_in_comp_(7.333, 10.0]"
0,True,False,False,True,True,False,False,False,False,False,...,True,False,False,False,True,False,False,True,False,False
1,True,False,False,True,True,False,False,False,False,False,...,False,False,True,False,False,True,False,False,True,False
2,True,False,False,True,True,False,False,False,False,False,...,False,False,True,False,False,False,True,True,False,False
3,True,False,False,True,True,False,False,False,False,False,...,False,False,True,False,False,True,False,False,True,False
4,True,False,False,True,True,False,False,False,False,False,...,False,True,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14990,True,False,False,True,True,False,False,False,False,False,...,True,False,False,False,True,False,False,True,False,False
14991,True,False,False,True,True,False,False,False,False,False,...,True,False,False,False,True,False,False,True,False,False
14992,True,False,False,True,True,False,False,False,False,False,...,True,False,False,False,True,False,False,True,False,False
14993,True,False,False,True,True,False,False,False,False,False,...,False,False,False,True,False,False,True,True,False,False
14994,True,False,False,True,True,False,False,False,False,False,...,True,False,False,False,True,False,False,True,False,False

In [18]:
itemsets = apriori(hr_trans, min_support=0.6,use_colnames=True)

rules = association_rules(itemsets , metric='confidence' , min_threshold=0.7)
rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift',]]
rules.sort_values(by=['confidence','lift','support'], ascending=False)

relv_rules= rules[rules['lift']>1]
relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

,antecedents,consequents,support,confidence,lift
18,"(yrs_in_comp_(1.992, 4.667], Work_accident_0)",(promotion_last_5years_0),0.686762,0.983572,1.004951
10,"(yrs_in_comp_(1.992, 4.667])",(promotion_last_5years_0),0.801467,0.981783,1.003123
3,(Work_accident_0),(promotion_last_5years_0),0.839146,0.981054,1.002378
24,"(yrs_in_comp_(1.992, 4.667], left_0)",(promotion_last_5years_0),0.634211,0.978899,1.000176
2,(promotion_last_5years_0),(Work_accident_0),0.839146,0.857386,1.002378
17,"(yrs_in_comp_(1.992, 4.667], promotion_last_5y...",(Work_accident_0),0.686762,0.856881,1.001788
25,"(promotion_last_5years_0, left_0)","(yrs_in_comp_(1.992, 4.667])",0.634211,0.854601,1.046871
9,(left_0),"(yrs_in_comp_(1.992, 4.667])",0.647883,0.850105,1.041363
20,"(yrs_in_comp_(1.992, 4.667])","(promotion_last_5years_0, Work_accident_0)",0.686762,0.841271,1.002532
27,(left_0),"(yrs_in_comp_(1.992, 4.667], promotion_last_5y...",0.634211,0.832167,1.038304
11,(promotion_last_5years_0),"(yrs_in_comp_(1.992, 4.667])",0.801467,0.818888,1.003123
19,"(promotion_last_5years_0, Work_accident_0)","(yrs_in_comp_(1.992, 4.667])",0.686762,0.818406,1.002532
22,(Work_accident_0),"(yrs_in_comp_(1.992, 4.667], promotion_last_5y...",0.686762,0.802900,1.001788
8,"(yrs_in_comp_(1.992, 4.667])",(left_0),0.647883,0.793644,1.041363
23,"(yrs_in_comp_(1.992, 4.667], promotion_last_5y...",(left_0),0.634211,0.791313,1.038304
26,"(yrs_in_comp_(1.992, 4.667])","(promotion_last_5years_0, left_0)",0.634211,0.776897,1.046871
21,(promotion_last_5years_0),"(yrs_in_comp_(1.992, 4.667], Work_accident_0)",0.686762,0.701690,1.004951

In [24]:
gen_rules(0.3,0.4)

,antecedents,consequents,support,confidence,lift
180,"(salary_low, yrs_in_comp_(1.992, 4.667], Work_...",(promotion_last_5years_0),0.341581,0.993213,1.014802
62,"(salary_low, Work_accident_0)",(promotion_last_5years_0),0.415138,0.992348,1.013918
133,"(salary_low, yrs_in_comp_(1.992, 4.667])",(promotion_last_5years_0),0.398866,0.991874,1.013434
26,(salary_low),(promotion_last_5years_0),0.483294,0.990975,1.012515
101,"(salary_low, left_0)",(promotion_last_5years_0),0.339580,0.989891,1.011408
...,...,...,...,...,...
198,"(yrs_in_comp_(1.992, 4.667], promotion_last_5y...","(project_(1.995, 3.667], Work_accident_0)",0.327776,0.408970,1.113179
138,(promotion_last_5years_0),"(salary_low, yrs_in_comp_(1.992, 4.667])",0.398866,0.407536,1.013434
188,"(promotion_last_5years_0, Work_accident_0)","(salary_low, yrs_in_comp_(1.992, 4.667])",0.341581,0.407057,1.012242
99,"(yrs_in_comp_(1.992, 4.667])","(project_(1.995, 3.667], Work_accident_0)",0.331911,0.406584,1.106686
201,"(yrs_in_comp_(1.992, 4.667])","(project_(1.995, 3.667], promotion_last_5years...",0.327776,0.401519,1.112282

In [19]:
from ipywidgets import interact
import ipywidgets as widgets

In [22]:
def gen_rules(min_support , minconfidence):
    itemsets = apriori(hr_trans, min_support=min_support, use_colnames=True)
    rules = association_rules(itemsets , metric='confidence' , min_threshold=minconfidence)
    rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift',]]
    relv_rules= rules[rules['lift']>1]
    return relv_rules.sort_values(by=['confidence','lift','support'], ascending=False)

In [23]:
interact(
    gen_rules , 
    min_support = widgets.FloatSlider(
        value = 0.2 , min = 0.01, max = 0.4 , step = 0.01 , description = 'Min Support:'
    ),
    minconfidence = widgets.FloatSlider(
        value = 0.2 , min = 0.01, max = 0.5 , step = 0.01, description = 'Min Confidence:'
    )
)

interactive(children=(FloatSlider(value=0.2, description='Min Support:', max=0.4, min=0.01, step=0.01), FloatS…