In [1]:
# embedding on content of news
import pandas as pd
import numpy as np
from tqdm import tqdm
from sentence_transformers import SentenceTransformer

In [4]:
df = pd.read_csv('historic_articles.csv')
df

,source,category,link,author,published_at,header,subheader,content
0,firstpost,india,https://www.firstpost.com/india/supreme-court-...,FP Staff,"September 21, 2020 20:11:56 IST","Supreme Court, in anti-CAA blockade case, says...",While listening to a batch of petitions agains...,The Supreme Court on Monday said there cannot ...
1,firstpost,india,https://www.firstpost.com/india/rti-reponse-re...,Sumit Chaturvedi,"September 20, 2020 10:02:10 IST",RTI reponse reveals over 18 lakh ration cards ...,The large backlog of pending ration card appli...,Lakhs of migrant workers who returned to their...
2,firstpost,india,https://www.firstpost.com/india/pilot-dies-as-...,Press Trust of India,"September 21, 2020 15:32:17 IST",Pilot dies as four-seater training aircraft cr...,"The aircraft, which belonged to the Indira Gan...",Azamgarh: A four-seater training aircraft cras...
3,firstpost,india,https://www.firstpost.com/india/hcl-technologi...,Press Trust of India,"September 21, 2020 14:15:16 IST",HCL Technologies to acquire Australia’s DWS Lt...,"DWS, with FY20 revenue at AUS $167.9 million, ...",New Delhi: HCL Technologies on Monday said it ...
4,firstpost,india,https://www.firstpost.com/india/parliament-mon...,FP Staff,"September 22, 2020 10:42:06 IST",Parliament LIVE Updates: Pralhad Joshi says go...,Parliament LIVE Updates: Parliamentary Affair ...,Parliament LATEST Updates: Parliamentary Affai...
...,...,...,...,...,...,...,...,...
1563,ndtv,world,https://www.ndtv.com/world-news/united-nations...,Reuters,"September 18, 2020 7:55 am IST",UN Asks Billionaires For Help As 270 Million P...,The combined wealth of America's billionaires ...,UN food chief David Beasley called on the worl...
1564,ndtv,world,https://www.ndtv.com/world-news/gunmen-kill-fi...,Agence France-Presse,"September 18, 2020 7:45 am IST",Gunmen Kill Five In Attack On Wake In Mexico,The assailants opened fire at a home in the ci...,Gunmen killed five people Thursday during an a...
1565,ndtv,world,https://www.ndtv.com/indians-abroad/us-congres...,Press Trust of India,"September 18, 2020 7:32 am IST",Deeply Concerned About India-China Border Issu...,"Over the past few months, top American lawmake...",An Indian-American Congressman has urged China...
1566,ndtv,world,https://www.ndtv.com/world-news/moderna-shares...,Agence France-Presse,"September 18, 2020 7:40 am IST","Moderna, Pfizer Share Covid Vaccine Trial Blue...","Pfizer, the other American company currently c...","US biotech firm Moderna, one of nine companies..."
1567,ndtv,world,https://www.ndtv.com/world-news/twitter-tighte...,Agence France-Presse,"September 18, 2020 5:20 am IST",Twitter Tightens Security For Politicians And ...,"""Implementing these security measures is a cri...",Twitter on Thursday said it is tightening secu...

In [5]:
df.shape
df.columns

Index(['source', 'category', 'link', 'author', 'published_at', 'header',
       'subheader', 'content'],
      dtype='object')

In [6]:
model = SentenceTransformer('BAAI/bge-small-en-v1.5')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  133MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [9]:
df_indian_movies = df[(df['category'].str.contains('india')) ]
df_indian_movies

,source,category,link,author,published_at,header,subheader,content
0,firstpost,india,https://www.firstpost.com/india/supreme-court-...,FP Staff,"September 21, 2020 20:11:56 IST","Supreme Court, in anti-CAA blockade case, says...",While listening to a batch of petitions agains...,The Supreme Court on Monday said there cannot ...
1,firstpost,india,https://www.firstpost.com/india/rti-reponse-re...,Sumit Chaturvedi,"September 20, 2020 10:02:10 IST",RTI reponse reveals over 18 lakh ration cards ...,The large backlog of pending ration card appli...,Lakhs of migrant workers who returned to their...
2,firstpost,india,https://www.firstpost.com/india/pilot-dies-as-...,Press Trust of India,"September 21, 2020 15:32:17 IST",Pilot dies as four-seater training aircraft cr...,"The aircraft, which belonged to the Indira Gan...",Azamgarh: A four-seater training aircraft cras...
3,firstpost,india,https://www.firstpost.com/india/hcl-technologi...,Press Trust of India,"September 21, 2020 14:15:16 IST",HCL Technologies to acquire Australia’s DWS Lt...,"DWS, with FY20 revenue at AUS $167.9 million, ...",New Delhi: HCL Technologies on Monday said it ...
4,firstpost,india,https://www.firstpost.com/india/parliament-mon...,FP Staff,"September 22, 2020 10:42:06 IST",Parliament LIVE Updates: Pralhad Joshi says go...,Parliament LIVE Updates: Parliamentary Affair ...,Parliament LATEST Updates: Parliamentary Affai...
...,...,...,...,...,...,...,...,...
1216,ndtv,india,https://www.ndtv.com/india-news/pm-narendra-mo...,Edited by Anindita Sanyal,"September 21, 2020 2:33 pm IST","""Some Fear Control Slipping Away"": PM Modi's D...","PM Narendra Modi said In Madhya Pradesh, Uttar...",Prime Minister Narendra Modi today said the pr...
1217,ndtv,india,https://www.ndtv.com/india-news/worlds-biggest...,(c) 2020 Bloomberg,(c) 2020 Bloomberg,World's Biggest Lockdown Chokes Indian Gold Sm...,Illegal shipments have been hit by one of the ...,The coronavirus pandemic has crushed the inflo...
1218,ndtv,india,https://www.ndtv.com/india-news/west-bengal-ch...,Press Trust of India,"September 21, 2020 12:37 pm IST","""BJP Killed Democracy"": Mamata Banerjee On Sus...",Mamata Banerjee calling the action reflective ...,The Trinamool Congress (TMC) has denounced the...
1219,ndtv,india,https://www.ndtv.com/india-news/digital-media-...,"Reported by A Vaidyanathan, Edited by Deepshik...","September 21, 2020 1:11 pm IST","Digital Media Spreading Venomous Hatred, Regul...",This is the government's second affidavit reco...,Digital media is spreading venomous hatred and...
1220,ndtv,india,https://www.ndtv.com/india-news/tablighi-jamaa...,Neeta Sharma,"September 21, 2020 12:36 pm IST","Tablighi Event Led To Covid Spread Among ""Many...",Hundreds of people - both foreigners and local...,A huge gathering of the Islamic sect Tablighi ...

In [11]:
all_content = list(df_indian_movies['content'].fillna(''))

out_embs = []  # this are vector embeddings which are generally stored in vector Databases like pinecone , Qdrant

for i in tqdm(all_content):
  enmd = model.encode(i)
  out_embs.append(enmd)
out_embs = np.array(out_embs)

100%|██████████| 415/415 [02:16<00:00,  3.05it/s]

In [12]:

df_embd = pd.DataFrame(out_embs )
df_embd

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.080176,0.023172,-0.065073,-0.003892,-0.039935,0.057297,0.049721,-0.043395,-0.016816,0.063032,...,-0.012366,0.007640,-0.046591,0.004088,-0.037538,0.053441,0.072454,-0.012145,-0.027155,0.045201
1,-0.042456,-0.023293,-0.039460,-0.002688,0.002964,0.000729,0.002834,-0.034946,-0.002039,-0.013722,...,0.028367,-0.083962,-0.000761,-0.033618,0.017383,0.003009,-0.014859,-0.005724,-0.004869,-0.021040
2,0.027668,0.034667,0.015557,0.005182,0.059439,0.047539,0.016233,0.070575,0.006830,-0.039830,...,0.114422,-0.013504,-0.004343,-0.005034,0.001847,-0.007111,0.075960,0.008050,0.018330,0.072456
3,-0.049505,0.044249,-0.085403,-0.015457,-0.007647,-0.018135,-0.003052,0.020355,-0.032147,-0.043342,...,-0.058308,0.060193,0.040579,-0.046835,-0.055323,0.094035,-0.017977,0.018738,0.017395,0.048383
4,-0.091977,0.032123,-0.028819,-0.004195,0.014297,0.005018,0.019205,-0.067136,0.024127,0.019334,...,-0.007596,-0.034530,0.011921,0.002243,0.024777,-0.017084,0.075972,0.007389,-0.043788,0.008372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,-0.067204,0.033826,-0.042343,0.065836,0.030702,-0.007573,-0.025126,-0.026642,0.007440,0.079239,...,-0.018619,-0.013586,-0.013801,-0.068190,0.008264,-0.020538,0.038938,0.008518,-0.043214,-0.027888
411,0.026388,-0.041066,0.022594,0.017445,0.047834,-0.020072,0.058550,-0.001496,-0.015558,0.008792,...,0.001683,-0.066556,-0.029742,0.023451,-0.004166,-0.036094,0.010932,-0.118606,-0.053329,0.012725
412,-0.012398,0.033320,-0.004734,-0.004455,0.025530,0.022302,0.048447,-0.028227,-0.031952,-0.000524,...,0.036880,-0.009440,-0.019651,-0.003942,0.021414,-0.018990,0.039302,-0.015682,0.004512,0.074141
413,-0.042568,0.000423,-0.066141,-0.065229,0.058927,0.025193,-0.040603,-0.023496,0.035474,0.015231,...,0.021414,0.035536,0.013405,0.086589,-0.041611,0.017134,0.011275,-0.033291,0.082378,0.075306
414,0.030713,0.048233,-0.030490,0.020137,0.054848,-0.010769,0.068032,-0.000413,0.011635,0.023891,...,-0.001550,-0.024866,0.004003,0.003842,0.024034,0.008816,0.015360,-0.004043,-0.001956,0.064551

In [ ]:
# see we have created df_indian_movies   and created df_embd   for that df_indian_movies
# model.encode always returns 384 columns as we are using SentenceTransformer('BAAI/bge-small-en-v1.5')

In [13]:
from sklearn.cluster import HDBSCAN
from sklearn.metrics import silhouette_score

In [14]:
hdbscan = HDBSCAN(min_cluster_size=2 )
hdbscan.fit(out_embs)
df_embd['hdbscan_cluster'] = hdbscan.labels_
df_embd['hdbscan_cluster'].value_counts()

hdbscan_cluster
-1     135
 75     18
 45     13
 58     12
 87      6
      ...
 28      2
 63      2
 18      2
 81      2
 15      2
Name: count, Length: 92, dtype: int64

In [26]:
# df_embd[df_embd['hdbscan_cluster']==75]

In [28]:
df_indian_movies[(df_embd['hdbscan_cluster'] == 45).values][['source' , 'category','content']]

        source category                                            content
12   firstpost    india  The Union Public Service Commission (UPSC) has...
16   firstpost    india  The All India AYUSH Post Graduation Entrance T...
22   firstpost    india  The National Testing Agency (NTA) will release...
29   firstpost    india  JEE Advanced 2020 | The Joint Entrance Examina...
61   firstpost    india  The UGC National Eligibility Test (NET) 2020 h...
68   firstpost    india  NATA 2020 | The Council of Architecture (CoA) ...
81   firstpost    india  The National Testing Agency (NTA) declared the...
84   firstpost    india  The University of Allahabad released the UGAT ...
141  firstpost    india  The Assam Science and Technology University (A...
152  firstpost    india  The official website of JEE Advanced 2020 entr...
159  firstpost    india  Indian Air Force has on Tuesday released the a...
161  firstpost    india  The Consortium of National Law Universities (C...
172  firstpost    india  The Lalit Narayan Mithila University (LNMU) ha...

In [32]:
df_indian_movies[(df_embd['hdbscan_cluster'] == 45).values]

,source,category,link,author,published_at,header,subheader,content
12,firstpost,india,https://www.firstpost.com/india/upsc-releases-...,FP Trending,"September 21, 2020 20:54:11 IST",UPSC releases admit card for Combined Geo-Scie...,The exam will be held in two shifts on 17 and ...,The Union Public Service Commission (UPSC) has...
16,firstpost,india,https://www.firstpost.com/india/nta-aiapget-20...,FP Trending,"September 21, 2020 18:06:30 IST",NTA AIAPGET 2020 releases admit card at ntaaia...,Students can download their hall ticket from n...,The All India AYUSH Post Graduation Entrance T...
22,firstpost,india,https://www.firstpost.com/india/jnuee-2020-adm...,FP Trending,"September 21, 2020 16:02:07 IST",JNUEE 2020 admit card to be released today at ...,Candidates who have enrolled for the admission...,The National Testing Agency (NTA) will release...
29,firstpost,india,https://www.firstpost.com/india/jee-advanced-2...,FP Trending,"September 21, 2020 12:35:16 IST",JEE Advanced 2020: Admit card released at jeea...,The Joint Entrance Examination (JEE) Advanced ...,JEE Advanced 2020 | The Joint Entrance Examina...
61,firstpost,india,https://www.firstpost.com/india/ugc-net-2020-a...,FP Staff,"September 19, 2020 19:08:43 IST",UGC NET 2020 Admit Card: NTA releases hall tic...,The National Testing Agency conducts the entra...,The UGC National Eligibility Test (NET) 2020 h...
68,firstpost,india,https://www.firstpost.com/india/nata-2020-seco...,FP Trending,"September 19, 2020 12:45:17 IST",NATA 2020 second test result declared; visit o...,NATA 2020 | The NATA second test result will h...,NATA 2020 | The Council of Architecture (CoA) ...
81,firstpost,india,https://www.firstpost.com/india/jee-main-2020-...,FP Trending,"September 18, 2020 22:03:39 IST","JEE Main 2020: NTA announces Paper 2 results, ...",Candidates who had appeared in the JEE (Main) ...,The National Testing Agency (NTA) declared the...
84,firstpost,india,https://www.firstpost.com/india/allahabad-univ...,FP Trending,"September 18, 2020 19:44:29 IST","Allahabad University releases UGAT, PGAT admit...",The Allahabad University will conduct the UGAT...,The University of Allahabad released the UGAT ...
141,firstpost,india,https://www.firstpost.com/india/assam-cee-2020...,FP Trending,"September 16, 2020 21:58:15 IST",Assam CEE 2020 admit card released; steps to d...,The Assam CEE 2020 will be conducted on 20 Sep...,The Assam Science and Technology University (A...
152,firstpost,india,https://www.firstpost.com/india/jee-advanced-2...,FP Trending,"September 16, 2020 17:38:04 IST",JEE Advanced 2020: Correction window opens for...,Registered candidates can change their choice ...,The official website of JEE Advanced 2020 entr...
159,firstpost,india,https://www.firstpost.com/india/afcat-2020-ind...,FP Trending,"September 16, 2020 13:55:14 IST",AFCAT 2020: Indian Air Force releases admit ca...,"As per the official website, the Air Force Com...",Indian Air Force has on Tuesday released the a...
161,firstpost,india,https://www.firstpost.com/india/clat-2020-admi...,FP Trending,"September 16, 2020 11:57:24 IST",CLAT 2020 admit card released at consortiumofn...,The consortium is responsible for the conduct ...,The Consortium of National Law Universities (C...
172,firstpost,india,https://www.firstpost.com/india/bihar-b-ed-cet...,FP Trending,"September 15, 2020 20:22:35 IST",Bihar B.Ed CET Admit Card 2020 released; here'...,The entrance exam is scheduled to be held from...,The Lalit Narayan Mithila University (LNMU) ha...