# load pretrained model and use it
Model Persistence (pickle.load): Loading a previously trained and saved model object (svm_model.pkl) into memory so you don't have to retrain it from scratch.


Model Inference (loaded_model.predict(df)): Feeding unseen test data (tst_cancer.csv) into the trained model to generate outputs (Malignant or Benign).



Training / Fitting (model.fit(...)): The model learns the underlying patterns, weights, and decision boundaries from your historical dataset.

Inference (model.predict(...)): The model applies those already-learned patterns to new, unseen data to generate predictions or classifications.

In [15]:
import pandas as pd
import numpy as np

import pickle
from sklearn.svm import SVC
import os
os.chdir('E:\PGCP-AI\PML\Cases\Wisconsin')

In [16]:
file = open('svm_model.pkl', 'rb')
loaded_model = pickle.load(file)

In [17]:
df = pd.read_csv('tst_cancer.csv',index_col=0)
df

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses
Code,,,,,,,,,
3444,5,4,3,1,3,2,2,3,10
3445,9,1,2,6,7,2,7,7,2
3446,9,4,8,2,2,4,6,1,1
3447,5,10,10,10,8,7,1,10,7
3448,1,10,1,1,2,5,5,1,1
3449,7,6,4,5,3,9,1,1,2

In [18]:
results = loaded_model.predict(df)
results

array(['Malignant', 'Malignant', 'Malignant', 'Malignant', 'Benign',
       'Malignant'], dtype=object)

In [19]:
df['predicted_results'] = results

In [20]:
df

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,predicted_results
Code,,,,,,,,,,
3444,5,4,3,1,3,2,2,3,10,Malignant
3445,9,1,2,6,7,2,7,7,2,Malignant
3446,9,4,8,2,2,4,6,1,1,Malignant
3447,5,10,10,10,8,7,1,10,7,Malignant
3448,1,10,1,1,2,5,5,1,1,Benign
3449,7,6,4,5,3,9,1,1,2,Malignant