In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('country_wise_latest.csv')
df.head(2)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe

In [6]:
print(df.isna().sum())

Country/Region            0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
Confirmed last week       0
1 week change             0
1 week % increase         0
WHO Region                0
dtype: int64

In [17]:
df['Country/Region'].unique().shape

(187,)

In [9]:
grps_by_country = df.groupby('Country/Region')

In [20]:
# What is the total global count of Confirmed, Deaths, Recovered, and Active cases across all countries?
df['Confirmed'].sum()

np.int64(16480485)

In [27]:
# Which top 10 countries have reported the highest total number of Confirmed cases?

df.sort_values(by='Confirmed',ascending=False).head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
138,Russia,816680,13334,602249,201097,5607,85,3077,1.63,73.74,2.21,776212,40468,5.21,Europe
154,South Africa,452529,7067,274925,170537,7096,298,9848,1.56,60.75,2.57,373628,78901,21.12,Africa
111,Mexico,395489,44022,303810,47657,4973,342,8588,11.13,76.82,14.49,349396,46093,13.19,Americas
132,Peru,389717,18418,272547,98752,13756,575,4697,4.73,69.93,6.76,357681,32036,8.96,Americas
35,Chile,347923,9187,319954,18782,2133,75,1859,2.64,91.96,2.87,333029,14894,4.47,Americas
177,United Kingdom,301708,45844,1437,254427,688,7,3,15.19,0.48,3190.26,296944,4764,1.60,Europe
81,Iran,293606,15912,255144,22550,2434,212,1931,5.42,86.90,6.24,276202,17404,6.30,Eastern Mediterranean

In [46]:
# Which top 10 countries have recorded the highest total number of Deaths?
df.sort_values(by='Deaths',ascending=False).head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
177,United Kingdom,301708,45844,1437,254427,688,7,3,15.19,0.48,3190.26,296944,4764,1.60,Europe
111,Mexico,395489,44022,303810,47657,4973,342,8588,11.13,76.82,14.49,349396,46093,13.19,Americas
85,Italy,246286,35112,198593,12581,168,5,147,14.26,80.64,17.68,244624,1662,0.68,Europe
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
61,France,220352,30212,81212,108928,2551,17,267,13.71,36.86,37.20,214023,6329,2.96,Europe
157,Spain,272421,28432,150376,93613,0,0,0,10.44,55.20,18.91,264836,7585,2.86,Europe
132,Peru,389717,18418,272547,98752,13756,575,4697,4.73,69.93,6.76,357681,32036,8.96,Americas
81,Iran,293606,15912,255144,22550,2434,212,1931,5.42,86.90,6.24,276202,17404,6.30,Eastern Mediterranean

2. Regional Analysis (WHO Regions)

In [62]:
# How are total Confirmed cases, Deaths, and Recovered cases distributed across the different WHO Region categories?
df.groupby('WHO Region')[['Confirmed','Deaths','Recovered']].agg('sum')

                       Confirmed  Deaths  Recovered
WHO Region
Africa                    723207   12223     440645
Americas                 8839286  342732    4468616
Eastern Mediterranean    1490744   38339    1201400
Europe                   3299523  211144    1993723
South-East Asia          1835297   41349    1156933
Western Pacific           292428    8249     206770

In [78]:
df[['WHO Region','Confirmed','Deaths','Recovered']].groupby('WHO Region').agg('sum')

                       Confirmed  Deaths  Recovered
WHO Region
Africa                    723207   12223     440645
Americas                 8839286  342732    4468616
Eastern Mediterranean    1490744   38339    1201400
Europe                   3299523  211144    1993723
South-East Asia          1835297   41349    1156933
Western Pacific           292428    8249     206770

In [92]:
df[['WHO Region','Deaths / 100 Cases']].groupby('WHO Region').agg(['sum'])

                      Deaths / 100 Cases
                                     sum
WHO Region
Africa                            110.71
Americas                          106.84
Eastern Mediterranean              78.39
Europe                            235.11
South-East Asia                    12.96
Western Pacific                    20.64

In [114]:
# Which WHO Region has the highest overall case fatality rate (Deaths / 100 Cases)?

df[['WHO Region','Deaths / 100 Cases']].groupby('WHO Region').agg(['sum'])['Deaths / 100 Cases'].sort_values(by='sum',ascending=False).head(1)

               sum
WHO Region
Europe      235.11

In [ ]:
# Which WHO Region experienced the highest average 1 week % increase in cases?

In [13]:
import numpy as np
import pandas as pd
import scipy 
data = np.array([2.1,3.2,3.8,4.0,4.9,5.1,5.8,6.2,6.9,7.3])
data

array([2.1, 3.2, 3.8, 4. , 4.9, 5.1, 5.8, 6.2, 6.9, 7.3])

In [14]:
mn = np.mean(data)
sd = np.std(data)
i = np.arange(1,10)
p = (i - 0.5) / 10

In [16]:
scipy.stats.norm.ppf(p)

array([-1.64485363, -1.03643339, -0.67448975, -0.38532047, -0.12566135,
        0.12566135,  0.38532047,  0.67448975,  1.03643339])

In [5]:
(data[1]-mn) / sd

np.float64(-1.0932519710522253)