### 1. Create a Series of 5 student names.

In [1]:
import pandas as pd

student_names = pd.Series(['Alice', 'Bob', 'Charlie', 'David', 'Eva'])
display(student_names)

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
dtype: object

### 2. Create a Series of 5 marks and display it.

In [2]:
marks = pd.Series([85, 92, 45, 78, 55])
display(marks)

0    85
1    92
2    45
3    78
4    55
dtype: int64

### 3. Create a Series with custom index labels like A, B, C, D.

In [ ]:
custom_series = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])
display(custom_series)a

A    10
B    20
C    30
D    40
dtype: int64

### 4. Access the third value from a Series.

In [4]:
third_val = student_names.iloc[2]
print("Third value:", third_val)

Third value: Charlie

### 5. Access a value from a Series using its custom label.

In [5]:
val_label = custom_series['C']
print("Value at label 'C':", val_label)

Value at label 'C': 30

### 6. Change one value in a Series.

In [6]:
student_names.iloc[1] = 'Bobby'
display(student_names)

0      Alice
1      Bobby
2    Charlie
3      David
4        Eva
dtype: object

### 7. Add 10 to every value in a numeric Series.

In [7]:
updated_marks = marks + 10
display(updated_marks)

0     95
1    102
2     55
3     88
4     65
dtype: int64

### 8. Find the maximum value in a Series.

In [8]:
max_val = marks.max()
print("Maximum mark:", max_val)

Maximum mark: 92

### 9. Find the minimum value in a Series.

In [9]:
min_val = marks.min()
print("Minimum mark:", min_val)

Minimum mark: 45

### 10. Find the mean of a numeric Series.

In [10]:
mean_val = marks.mean()
print("Mean mark:", mean_val)

Mean mark: 71.0

### 11. Filter only values greater than 50 in a Series.

In [11]:
filtered_marks = marks[marks > 50]
display(filtered_marks)

0    85
1    92
3    78
4    55
dtype: int64

### 12. Create a Series from a dictionary.

In [12]:
dict_data = {'Maths': 90, 'Science': 88, 'English': 76}
series_from_dict = pd.Series(dict_data)
display(series_from_dict)

Maths      90
Science    88
English    76
dtype: int64

### 13. Check the index of a Series.

In [13]:
print("Series Index:", custom_series.index)

Series Index: Index(['A', 'B', 'C', 'D'], dtype='object')

### 14. Check the values of a Series.

In [14]:
print("Series Values:", custom_series.values)

Series Values: [10 20 30 40]

### 15. Convert a Series into a list.

In [15]:
marks_list = marks.tolist()
print("Marks List:", marks_list)

Marks List: [85, 92, 45, 78, 55]

### 16. Check which values in a Series are null.

In [16]:
null_series = pd.Series([10, None, 30, None])
display(null_series.isnull())

0    False
1     True
2    False
3     True
dtype: bool

### 17. Fill missing values in a Series with 0.

In [17]:
filled_series = null_series.fillna(0)
display(filled_series)

0    10.0
1     0.0
2    30.0
3     0.0
dtype: float64

### 18. Count how many times each value appears in a Series.

In [18]:
dup_series = pd.Series(['A', 'B', 'A', 'C', 'B', 'A'])
display(dup_series.value_counts())

A    3
B    2
C    1
Name: count, dtype: int64

### 19. Sort a Series by values.

In [19]:
sorted_by_values = marks.sort_values()
display(sorted_by_values)

2    45
4    55
3    78
0    85
1    92
dtype: int64

### 20. Sort a Series by index.

In [20]:
unordered_series = pd.Series([1, 2, 3], index=['Z', 'Y', 'X'])
display(unordered_series.sort_index())

X    3
Y    2
Z    1
dtype: int64

### 21. Create a DataFrame of 5 students with columns Name, Age, Marks.

In [21]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [19, 21, 18, 20, 22],
    'Marks': [85, 92, 35, 78, 55]
}
df = pd.DataFrame(data)
display(df)

      Name  Age  Marks
0    Alice   19     85
1      Bob   21     92
2  Charlie   18     35
3    David   20     78
4      Eva   22     55

### 22. Display the first 3 rows of a DataFrame.

In [22]:
display(df.head(3))

      Name  Age  Marks
0    Alice   19     85
1      Bob   21     92
2  Charlie   18     35

### 23. Display the last 2 rows of a DataFrame.

In [23]:
display(df.tail(2))

    Name  Age  Marks
3  David   20     78
4    Eva   22     55

### 24. Display only one column from a DataFrame.

In [24]:
display(df['Name'])

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object

### 25. Display two columns from a DataFrame.

In [25]:
display(df[['Name', 'Marks']])

      Name  Marks
0    Alice     85
1      Bob     92
2  Charlie     35
3    David     78
4      Eva     55

### 26. Add a new column called Passed based on Marks > 40.

In [26]:
df['Passed'] = df['Marks'] > 40
display(df)

      Name  Age  Marks  Passed
0    Alice   19     85    True
1      Bob   21     92    True
2  Charlie   18     35   False
3    David   20     78    True
4      Eva   22     55    True

### 27. Add a new column called Bonus with fixed value 5.

In [27]:
df['Bonus'] = 5
display(df)

      Name  Age  Marks  Passed  Bonus
0    Alice   19     85    True      5
1      Bob   21     92    True      5
2  Charlie   18     35   False      5
3    David   20     78    True      5
4      Eva   22     55    True      5

### 28. Change the values of one existing column.

In [28]:
df['Bonus'] = 10
display(df)

      Name  Age  Marks  Passed  Bonus
0    Alice   19     85    True     10
1      Bob   21     92    True     10
2  Charlie   18     35   False     10
3    David   20     78    True     10
4      Eva   22     55    True     10

### 29. Delete one column from a DataFrame.

In [29]:
df_dropped = df.drop(columns=['Bonus'])
display(df_dropped)

      Name  Age  Marks  Passed
0    Alice   19     85    True
1      Bob   21     92    True
2  Charlie   18     35   False
3    David   20     78    True
4      Eva   22     55    True

### 30. Rename a column in a DataFrame.

In [30]:
df_renamed = df.rename(columns={'Marks': 'Score'})
display(df_renamed)

      Name  Age  Score  Passed  Bonus
0    Alice   19     85    True     10
1      Bob   21     92    True     10
2  Charlie   18     35   False     10
3    David   20     78    True     10
4      Eva   22     55    True     10

### 31. Set Name as index of the DataFrame.

In [31]:
df_indexed = df.set_index('Name')
display(df_indexed)

         Age  Marks  Passed  Bonus
Name
Alice     19     85    True     10
Bob       21     92    True     10
Charlie   18     35   False     10
David     20     78    True     10
Eva       22     55    True     10

### 32. Reset the index back to default integers.

In [32]:
df_reset = df_indexed.reset_index()
display(df_reset)

      Name  Age  Marks  Passed  Bonus
0    Alice   19     85    True     10
1      Bob   21     92    True     10
2  Charlie   18     35   False     10
3    David   20     78    True     10
4      Eva   22     55    True     10

### 33. Select the first row using iloc.

In [33]:
first_row = df.iloc[0]
display(first_row)

Name      Alice
Age          19
Marks        85
Passed     True
Bonus        10
Name: 0, dtype: object

### 34. Select a row using loc with label index.

In [34]:
row_label = df_indexed.loc['Charlie']
display(row_label)

Age          18
Marks        35
Passed    False
Bonus        10
Name: Charlie, dtype: object

### 35. Filter students with Marks greater than 60.

In [35]:
high_scorers = df[df['Marks'] > 60]
display(high_scorers)

    Name  Age  Marks  Passed  Bonus
0  Alice   19     85    True     10
1    Bob   21     92    True     10
3  David   20     78    True     10

### 36. Filter students whose Age is less than 20.

In [36]:
young_students = df[df['Age'] < 20]
display(young_students)

      Name  Age  Marks  Passed  Bonus
0    Alice   19     85    True     10
2  Charlie   18     35   False     10

### 37. Find the average Marks of all students.

In [37]:
average_marks = df['Marks'].mean()
print("Average Marks:", average_marks)

Average Marks: 69.0

### 38. Find the student with highest Marks.

In [38]:
highest_marks_student = df.loc[df['Marks'].idxmax()]
display(highest_marks_student)

Name       Bob
Age         21
Marks       92
Passed    True
Bonus       10
Name: 1, dtype: object

### 39. Sort the DataFrame by Marks in ascending order.

In [39]:
sorted_by_marks = df.sort_values(by='Marks')
display(sorted_by_marks)

      Name  Age  Marks  Passed  Bonus
2  Charlie   18     35   False     10
4      Eva   22     55    True     10
3    David   20     78    True     10
0    Alice   19     85    True     10
1      Bob   21     92    True     10

### 40. Sort the DataFrame by Age in descending order.

In [40]:
sorted_by_age_desc = df.sort_values(by='Age', ascending=False)
display(sorted_by_age_desc)

      Name  Age  Marks  Passed  Bonus
4      Eva   22     55    True     10
1      Bob   21     92    True     10
3    David   20     78    True     10
0    Alice   19     85    True     10
2  Charlie   18     35   False     10

### 41. Check DataFrame shape.

In [41]:
print("DataFrame Shape:", df.shape)

DataFrame Shape: (5, 5)

### 42. Check DataFrame column names.

In [42]:
print("Columns:", df.columns)

Columns: Index(['Name', 'Age', 'Marks', 'Passed', 'Bonus'], dtype='object')

### 43. Check DataFrame data types.

In [43]:
print(df.dtypes)

Name      object
Age        int64
Marks      int64
Passed      bool
Bonus      int64
dtype: object

### 44. Check if any values are missing in the DataFrame.

In [44]:
display(df.isnull().sum())

Name      0
Age       0
Marks     0
Passed    0
Bonus     0
dtype: int64

### 45. Fill missing values in Marks with the column mean.

In [45]:
df_missing = df.copy()
df_missing.loc[2, 'Marks'] = None
df_missing['Marks'] = df_missing['Marks'].fillna(df_missing['Marks'].mean())
display(df_missing)

      Name  Age  Marks  Passed  Bonus
0    Alice   19   85.0    True     10
1      Bob   21   92.0    True     10
2  Charlie   18   77.5   False     10
3    David   20   78.0    True     10
4      Eva   22   55.0    True     10

### 46. Drop rows containing missing values.

In [46]:
df_dirty = df.copy()
df_dirty.loc[2, 'Marks'] = None
df_clean = df_dirty.dropna()
display(df_clean)

    Name  Age  Marks  Passed  Bonus
0  Alice   19   85.0    True     10
1    Bob   21   92.0    True     10
3  David   20   78.0    True     10
4    Eva   22   55.0    True     10

### 47. Count unique values in a column.

In [47]:
num_unique_ages = df['Age'].nunique()
print("Unique ages:", num_unique_ages)

Unique ages: 5

### 48. Find value counts of a categorical column like Department.

In [48]:
df['Department'] = ['CS', 'EC', 'CS', 'ME', 'EC']
display(df['Department'].value_counts())

Department
CS    2
EC    2
ME    1
Name: count, dtype: int64

### 49. Create a second DataFrame and concatenate it with the first one.

In [49]:
df2 = pd.DataFrame({
    'Name': ['Fiona', 'George'],
    'Age': [23, 20],
    'Marks': [91, 64],
    'Passed': [True, True],
    'Bonus': [10, 10],
    'Department': ['CS', 'ME']
})
concatenated_df = pd.concat([df, df2], ignore_index=True)
display(concatenated_df)

      Name  Age  Marks  Passed  Bonus Department
0    Alice   19     85    True     10         CS
1      Bob   21     92    True     10         EC
2  Charlie   18     35   False     10         CS
3    David   20     78    True     10         ME
4      Eva   22     55    True     10         EC
5    Fiona   23     91    True     10         CS
6   George   20     64    True     10         ME

### 50. Create two DataFrames with a common column and merge them.

In [50]:
student_details = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami']
})
merged_df = pd.merge(df, student_details, on='Name')
display(merged_df)

      Name  Age  Marks  Passed  Bonus Department         City
0    Alice   19     85    True     10         CS     New York
1      Bob   21     92    True     10         EC  Los Angeles
2  Charlie   18     35   False     10         CS      Chicago
3    David   20     78    True     10         ME      Houston
4      Eva   22     55    True     10         EC        Miami