In [75]:
import pandas as pd
import numpy as np
from datetime import datetime, date, time
from pandas.tseries.holiday import USFederalHolidayCalendar

### Question 1
Write a Pandas program to create
a) Datetime object for Jan 15 2012.
b) Specific date and time of 9:20 pm.
c) Local date and time.
d) A date without time.
e) Current date.
f) Time from a datetime.
g) Current local time.

In [76]:
dt1 = pd.to_datetime('Jan 15 2012')
dt2 = pd.to_datetime('21:20:00').time()
dt3 = datetime.now()
dt4 = date(2012, 1, 15)
dt5 = date.today()
dt6 = datetime.now().time()
dt7 = datetime.now().time()

(dt1, dt2, dt3, dt4, dt5, dt6, dt7)

(Timestamp('2012-01-15 00:00:00'),
 datetime.time(21, 20),
 datetime.datetime(2026, 10, 9, 9, 46, 22, 132524),
 datetime.date(2012, 1, 15),
 datetime.date(2026, 10, 9),
 datetime.time(9, 46, 22, 132661),
 datetime.time(9, 46, 22, 132694))

### Question 2
Write a Pandas program to create
a) a specific date using timestamp.
b) date and time using timestamp.
c) a time adds in the current local date using timestamp.
d) current date and time using timestamp.

In [77]:
ts_a = pd.Timestamp('2023-10-01')
ts_b = pd.Timestamp('2023-10-01 14:30:00')
ts_c = pd.Timestamp(date.today()) + pd.Timedelta(hours=5)
ts_d = pd.Timestamp.now()

(ts_a, ts_b, ts_c, ts_d)

(Timestamp('2023-10-01 00:00:00'),
 Timestamp('2023-10-01 14:30:00'),
 Timestamp('2026-10-09 05:00:00'),
 Timestamp('2026-10-09 09:46:22.143255'))

### Question 3
Write a Pandas program to create a date from a given year, month, day and another date from a given string formats.

In [78]:
df_date = pd.DataFrame({'year': [2020], 'month': [5], 'day': [17]})
date_from_comp = pd.to_datetime(df_date).iloc[0]
date_from_str = pd.to_datetime('17-05-2020', format='%d-%m-%Y')

(date_from_comp, date_from_str)

(Timestamp('2020-05-17 00:00:00'), Timestamp('2020-05-17 00:00:00'))

### Question 4
Write a Pandas program to print the day after and before a specified date. Also print the days between two given dates.

In [79]:
spec_date = pd.to_datetime('2023-05-15')
day_before = spec_date - pd.Timedelta(days=1)
day_after = spec_date + pd.Timedelta(days=1)

date1 = pd.to_datetime('2023-05-10')
date2 = pd.to_datetime('2023-05-20')
days_between = pd.date_range(start=date1 + pd.Timedelta(days=1), end=date2 - pd.Timedelta(days=1)).tolist()

(day_before, day_after, days_between)

(Timestamp('2023-05-14 00:00:00'),
 Timestamp('2023-05-16 00:00:00'),
 [Timestamp('2023-05-11 00:00:00'),
  Timestamp('2023-05-12 00:00:00'),
  Timestamp('2023-05-13 00:00:00'),
  Timestamp('2023-05-14 00:00:00'),
  Timestamp('2023-05-15 00:00:00'),
  Timestamp('2023-05-16 00:00:00'),
  Timestamp('2023-05-17 00:00:00'),
  Timestamp('2023-05-18 00:00:00'),
  Timestamp('2023-05-19 00:00:00')])

### Question 5
Write a Pandas program to create a time-series with two index labels and random values. Also print the type of the index.

In [80]:
index_labels = pd.to_datetime(['2023-01-01', '2023-01-02'])
ts = pd.Series(np.random.randn(2), index=index_labels)

display(ts)
type(ts.index)

2023-01-01    0.306544
2023-01-02    0.389142
dtype: float64

pandas.core.indexes.datetimes.DatetimeIndex

### Question 6
Write a Pandas program to create a time-series from a given list of dates as strings.

In [81]:
date_strings = ['2023-01-01', '2023-01-03', '2023-01-05']
ts_from_strings = pd.Series(np.random.randn(3), index=pd.to_datetime(date_strings))
ts_from_strings

2023-01-01    1.846965
2023-01-03   -0.430609
2023-01-05   -0.753034
dtype: float64

### Question 7
Write a Pandas program to create a time series object that has time indexed data. Also select the dates of same year and select the dates between certain dates.

In [82]:
dates = pd.to_datetime(['2022-05-10', '2022-08-15', '2023-01-10', '2023-04-20'])
ts_time = pd.Series(range(4), index=dates)
same_year = ts_time['2022']
between_dates = ts_time['2022-06-01':'2023-02-01']

(same_year, between_dates)

(2022-05-10    0
 2022-08-15    1
 dtype: int64,
 2022-08-15    1
 2023-01-10    2
 dtype: int64)

### Question 8
Write a Pandas program to create a date range using a startpoint date and a number of periods.

In [83]:
pd.date_range(start='2023-01-01', periods=5)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05'],
              dtype='datetime64[ns]', freq='D')

### Question 9
Write a Pandas program to create a whole month of dates in daily frequencies. Also find the maximum, minimum timestamp and indexs.

In [84]:
month_dates = pd.date_range(start='2023-05-01', end='2023-05-31', freq='D')
min_ts, min_idx = month_dates.min(), month_dates.argmin()
max_ts, max_idx = month_dates.max(), month_dates.argmax()

(min_ts, min_idx, max_ts, max_idx)

(Timestamp('2023-05-01 00:00:00'),
 np.int64(0),
 Timestamp('2023-05-31 00:00:00'),
 np.int64(30))

### Question 10
Write a Pandas program to create a time series using three months frequency.

In [85]:
pd.date_range(start='2023-01-01', periods=4, freq='3ME')

DatetimeIndex(['2023-01-31', '2023-04-30', '2023-07-31', '2023-10-31'], dtype='datetime64[ns]', freq='3ME')

### Question 11
Write a Pandas program to create a sequence of durations increasing by an hour.

In [86]:
pd.timedelta_range(start='0 hours', periods=5, freq='h')

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00'],
               dtype='timedelta64[ns]', freq='h')

### Question 12
Write a Pandas program to convert year and day of year into a single datetime column of a dataframe.

In [87]:
df_doy = pd.DataFrame({'year': [2020, 2021], 'day_of_year': [100, 200]})
df_doy['datetime'] = pd.to_datetime(df_doy['year'].astype(str) + '-' + df_doy['day_of_year'].astype(str), format='%Y-%j')
df_doy

   year  day_of_year   datetime
0  2020          100 2020-04-09
1  2021          200 2021-07-19

### Question 13
Write a Pandas program to create a series of Timestamps from a DataFrame of integer or string columns. Also create a series of Timestamps using specified columns.

In [88]:
df_comp = pd.DataFrame({'year': [2020, 2021], 'month': [2, 6], 'day': [10, 15]})
pd.to_datetime(df_comp[['year', 'month', 'day']])

0   2020-02-10
1   2021-06-15
dtype: datetime64[ns]

### Question 14
Write a Pandas program to check if a day is a business day (weekday) or not.

In [89]:
def is_business_day(date_val):
    return pd.bdate_range(date_val, date_val).size > 0

test_date1 = pd.to_datetime('2023-10-14')
test_date2 = pd.to_datetime('2023-10-16')

(is_business_day(test_date1), is_business_day(test_date2))

(False, True)

### Question 15
Write a Pandas program to get a time series with the last working days of each month of a specific year.

In [90]:
pd.date_range(start='2023-01-01', end='2023-12-31', freq='BME')

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-28',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-29', '2023-10-31', '2023-11-30', '2023-12-29'],
              dtype='datetime64[ns]', freq='BME')

### Question 16
Write a Pandas program to create a time series combining hour and minute.

In [91]:
times = pd.date_range("2023-01-01", periods=4, freq="h") + pd.Timedelta(minutes=30)
times.time

array([datetime.time(0, 30), datetime.time(1, 30), datetime.time(2, 30),
       datetime.time(3, 30)], dtype=object)

### Question 17
Write a Pandas program to convert unix/epoch time to a regular time stamp in UTC. Also convert the said timestamp in to a given time zone.

In [92]:
epoch_time = 1609459200
utc_ts = pd.to_datetime(epoch_time, unit='s', utc=True)
tz_converted = utc_ts.tz_convert('US/Eastern')

(utc_ts, tz_converted)

(Timestamp('2021-01-01 00:00:00+0000', tz='UTC'),
 Timestamp('2020-12-31 19:00:00-0500', tz='US/Eastern'))

### Question 18
Write a Pandas program to create a time series object with a time zone.

In [93]:
pd.date_range('2023-01-01', periods=3, freq='D', tz='UTC')

DatetimeIndex(['2023-01-01 00:00:00+00:00', '2023-01-02 00:00:00+00:00',
               '2023-01-03 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='D')

### Question 19
Write a Pandas program to remove the time zone information from a Time series data.

In [94]:
ts_tz = pd.date_range('2023-01-01', periods=3, freq='D', tz='UTC')
ts_tz.tz_localize(None)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03'], dtype='datetime64[ns]', freq=None)

### Question 20
Write a Pandas program to subtract two timestamps of same time zone or different time zone.

In [95]:
t1 = pd.Timestamp('2023-01-02 12:00:00', tz='UTC')
t2 = pd.Timestamp('2023-01-01 12:00:00', tz='UTC')
t3 = pd.Timestamp('2023-01-01 12:00:00', tz='US/Eastern')

diff_same_tz = t1 - t2
diff_diff_tz = t1 - t3.tz_convert('UTC')

(diff_same_tz, diff_diff_tz)

(Timedelta('1 days 00:00:00'), Timedelta('0 days 19:00:00'))

### Question 21
Write a Pandas program to calculate all Thursdays between two given days.

In [96]:
pd.date_range(start='2023-10-01', end='2023-11-01', freq='W-THU')

DatetimeIndex(['2023-10-05', '2023-10-12', '2023-10-19', '2023-10-26'], dtype='datetime64[ns]', freq='W-THU')

### Question 22
Write a Pandas program to find the all the business quarterly begin and end dates of a specified year.

In [97]:
q_begins = pd.date_range(start='2023-01-01', end='2023-12-31', freq='BQS')
q_ends = pd.date_range(start='2023-01-01', end='2023-12-31', freq='BQE')

(q_begins, q_ends)

(DatetimeIndex(['2023-01-02', '2023-04-03', '2023-07-03', '2023-10-02'], dtype='datetime64[ns]', freq='BQS-JAN'),
 DatetimeIndex(['2023-03-31', '2023-06-30', '2023-09-29', '2023-12-29'], dtype='datetime64[ns]', freq='BQE-DEC'))

### Question 23
Write a Pandas program to generate sequences of fixed-frequency dates and time spans intervals.

In [98]:
fixed_dates = pd.date_range('2023-01-01', periods=3, freq='2h')
spans = pd.period_range('2023-01', periods=3, freq='M')

(fixed_dates, spans)

(DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 02:00:00',
                '2023-01-01 04:00:00'],
               dtype='datetime64[ns]', freq='2h'),
 PeriodIndex(['2023-01', '2023-02', '2023-03'], dtype='period[M]'))

### Question 24
Write a Pandas program to generate time series combining day and intraday offsets intervals.

In [99]:
pd.date_range('2023-01-01', periods=3, freq='1D2h')

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-02 02:00:00',
               '2023-01-03 04:00:00'],
              dtype='datetime64[ns]', freq='26h')

### Question 25
Write a Pandas program to extract the day name from a specified date. Add 2 days and 1 business day with the specified date.

In [100]:
base_date = pd.to_datetime('2023-10-13')
day_name = base_date.day_name()
plus_2_days = base_date + pd.Timedelta(days=2)
plus_1_bday = base_date + pd.offsets.BusinessDay(1)

(day_name, plus_2_days, plus_1_bday)

('Friday', Timestamp('2023-10-15 00:00:00'), Timestamp('2023-10-16 00:00:00'))

### Question 26
Write a Pandas program to convert integer or float epoch times to Timestamp and DatetimeIndex.

In [101]:
epoch_val = 1609459200.5
ts_val = pd.to_datetime(epoch_val, unit='s')
dt_index = pd.to_datetime([1609459200, 1609545600], unit='s')

(ts_val, dt_index)

(Timestamp('2021-01-01 00:00:00.500000'),
 DatetimeIndex(['2021-01-01', '2021-01-02'], dtype='datetime64[ns]', freq=None))

### Question 27
Write a Pandas program to calculate one, two, three business day(s) from a specified date. Also find the next business month end from a specific date.

In [102]:
s_date = pd.to_datetime('2023-10-13')
b1 = s_date + pd.offsets.BusinessDay(1)
b2 = s_date + pd.offsets.BusinessDay(2)
b3 = s_date + pd.offsets.BusinessDay(3)
next_bm_end = s_date + pd.offsets.BMonthEnd(1)

(b1, b2, b3, next_bm_end)

(Timestamp('2023-10-16 00:00:00'),
 Timestamp('2023-10-17 00:00:00'),
 Timestamp('2023-10-18 00:00:00'),
 Timestamp('2023-10-31 00:00:00'))

### Question 28
Write a Pandas program to create a period index represent all monthly boundaries of a given year. Also print start and end time for each period object in the said index.

In [103]:
period_idx = pd.period_range(start='2023-01', end='2023-12', freq='M')
[(p, p.start_time, p.end_time) for p in period_idx]

[(Period('2023-01', 'M'),
  Timestamp('2023-01-01 00:00:00'),
  Timestamp('2023-01-31 23:59:59.999999999')),
 (Period('2023-02', 'M'),
  Timestamp('2023-02-01 00:00:00'),
  Timestamp('2023-02-28 23:59:59.999999999')),
 (Period('2023-03', 'M'),
  Timestamp('2023-03-01 00:00:00'),
  Timestamp('2023-03-31 23:59:59.999999999')),
 (Period('2023-04', 'M'),
  Timestamp('2023-04-01 00:00:00'),
  Timestamp('2023-04-30 23:59:59.999999999')),
 (Period('2023-05', 'M'),
  Timestamp('2023-05-01 00:00:00'),
  Timestamp('2023-05-31 23:59:59.999999999')),
 (Period('2023-06', 'M'),
  Timestamp('2023-06-01 00:00:00'),
  Timestamp('2023-06-30 23:59:59.999999999')),
 (Period('2023-07', 'M'),
  Timestamp('2023-07-01 00:00:00'),
  Timestamp('2023-07-31 23:59:59.999999999')),
 (Period('2023-08', 'M'),
  Timestamp('2023-08-01 00:00:00'),
  Timestamp('2023-08-31 23:59:59.999999999')),
 (Period('2023-09', 'M'),
  Timestamp('2023-09-01 00:00:00'),
  Timestamp('2023-09-30 23:59:59.999999999')),
 (Period('2023-10', 'M'),
  Timestamp('2023-10-01 00:00:00'),
  Timestamp('2023-10-31 23:59:59.999999999')),
 (Period('2023-11', 'M'),
  Timestamp('2023-11-01 00:00:00'),
  Timestamp('2023-11-30 23:59:59.999999999')),
 (Period('2023-12', 'M'),
  Timestamp('2023-12-01 00:00:00'),
  Timestamp('2023-12-31 23:59:59.999999999'))]

### Question 29
Write a Pandas program create a series with a PeriodIndex which represents all the calendar month periods in 2029 and 2031. Also print the values for all periods in 2030.

In [104]:
all_periods = pd.period_range(start='2029-01', end='2031-12', freq='M')
series_periods = pd.Series(range(len(all_periods)), index=all_periods)
series_periods['2030']

2030-01    12
2030-02    13
2030-03    14
2030-04    15
2030-05    16
2030-06    17
2030-07    18
2030-08    19
2030-09    20
2030-10    21
2030-11    22
2030-12    23
Freq: M, dtype: int64

### Question 30
Write a Pandas program to generate holidays between two dates using the US federal holiday calendar.

In [105]:
cal = USFederalHolidayCalendar()
cal.holidays(start='2023-01-01', end='2023-12-31')

DatetimeIndex(['2023-01-02', '2023-01-16', '2023-02-20', '2023-05-29',
               '2023-06-19', '2023-07-04', '2023-09-04', '2023-10-09',
               '2023-11-10', '2023-11-23', '2023-12-25'],
              dtype='datetime64[ns]', freq=None)

### Question 31
Write a Pandas program to create a monthly time period and display the list of names in the current local scope.

In [106]:
monthly_period = pd.Period('2023-10', freq='M')
[name for name in dir() if 'monthly' in name.lower()]

['monthly_period']

### Question 32
Write a Pandas program to create a yearly time period from a specified year and display the properties of this period.

In [107]:
yearly_period = pd.Period('2023', freq='Y')
(yearly_period, yearly_period.start_time, yearly_period.end_time, yearly_period.is_leap_year)

(Period('2023', 'Y-DEC'),
 Timestamp('2023-01-01 00:00:00'),
 Timestamp('2023-12-31 23:59:59.999999999'),
 False)