In [19]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import linkage, dendrogram
from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import os
os.chdir(r'E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets')

In [20]:
df = pd.read_csv('milk.csv', index_col = 0)
df

            water  protein   fat  lactose   ash
Animal
HORSE        90.1      2.6   1.0      6.9  0.35
ORANGUTAN    88.5      1.4   3.5      6.0  0.24
MONKEY       88.4      2.2   2.7      6.4  0.18
DONKEY       90.3      1.7   1.4      6.2  0.40
HIPPO        90.4      0.6   4.5      4.4  0.10
CAMEL        87.7      3.5   3.4      4.8  0.71
BISON        86.9      4.8   1.7      5.7  0.90
BUFFALO      82.1      5.9   7.9      4.7  0.78
GUINEA PIG   81.9      7.4   7.2      2.7  0.85
CAT          81.6     10.1   6.3      4.4  0.75
FOX          81.6      6.6   5.9      4.9  0.93
LLAMA        86.5      3.9   3.2      5.6  0.80
MULE         90.0      2.0   1.8      5.5  0.47
PIG          82.8      7.1   5.1      3.7  1.10
ZEBRA        86.2      3.0   4.8      5.3  0.70
SHEEP        82.0      5.6   6.4      4.7  0.91
DOG          76.3      9.3   9.5      3.0  1.20
ELEPHANT     70.7      3.6  17.6      5.6  0.63
RABBIT       71.3     12.3  13.1      1.9  2.30
RAT          72.5      9.2  12.6      3.3  1.40
DEER         65.9     10.4  19.7      2.6  1.40
REINDEER     64.8     10.7  20.3      2.5  1.40
WHALE        64.8     11.1  21.2      1.6  1.70
SEAL         46.4      9.7  42.0      0.0  0.85
DOLPHIN      44.9     10.6  34.9      0.9  0.53

In [21]:
scaler = StandardScaler().set_output(transform='pandas')
df_scaled = scaler.fit_transform(df)

In [29]:
hc = AgglomerativeClustering(n_clusters=3)
hc.fit(df_scaled)
# hc.labels_
silhouette_score(df_scaled,hc.labels_)

0.5391595072079529

In [33]:
clusters= [ 2,3,4,5,6,7]
scores = []
for c in clusters:
    hc = AgglomerativeClustering(n_clusters=c)
    hc.fit(df_scaled)
    # hc.labels_
    scores.append([c , silhouette_score(df_scaled,hc.labels_)])

df_score = pd.DataFrame(scores , columns = ['clusters', 'score'])
df_score.sort_values(by='score', ascending=False)

   clusters     score
1         3  0.539160
0         2  0.525851
2         4  0.443481
3         5  0.398301
5         7  0.380407
4         6  0.375007

In [34]:
df = df.copy()
df['Cluster'] = hc.labels_
df

            water  protein   fat  lactose   ash  Cluster
Animal
HORSE        90.1      2.6   1.0      6.9  0.35        3
ORANGUTAN    88.5      1.4   3.5      6.0  0.24        3
MONKEY       88.4      2.2   2.7      6.4  0.18        3
DONKEY       90.3      1.7   1.4      6.2  0.40        3
HIPPO        90.4      0.6   4.5      4.4  0.10        3
CAMEL        87.7      3.5   3.4      4.8  0.71        4
BISON        86.9      4.8   1.7      5.7  0.90        4
BUFFALO      82.1      5.9   7.9      4.7  0.78        1
GUINEA PIG   81.9      7.4   7.2      2.7  0.85        1
CAT          81.6     10.1   6.3      4.4  0.75        1
FOX          81.6      6.6   5.9      4.9  0.93        1
LLAMA        86.5      3.9   3.2      5.6  0.80        4
MULE         90.0      2.0   1.8      5.5  0.47        3
PIG          82.8      7.1   5.1      3.7  1.10        1
ZEBRA        86.2      3.0   4.8      5.3  0.70        4
SHEEP        82.0      5.6   6.4      4.7  0.91        1
DOG          76.3      9.3   9.5      3.0  1.20        0
ELEPHANT     70.7      3.6  17.6      5.6  0.63        6
RABBIT       71.3     12.3  13.1      1.9  2.30        5
RAT          72.5      9.2  12.6      3.3  1.40        0
DEER         65.9     10.4  19.7      2.6  1.40        0
REINDEER     64.8     10.7  20.3      2.5  1.40        0
WHALE        64.8     11.1  21.2      1.6  1.70        0
SEAL         46.4      9.7  42.0      0.0  0.85        2
DOLPHIN      44.9     10.6  34.9      0.9  0.53        2