In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier  
from sklearn.linear_model import LogisticRegression, LinearRegression 
from sklearn.neighbors import KNeighborsClassifier , KNeighborsRegressor
from sklearn.ensemble import AdaBoostClassifier ,GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score,r2_score  
from tqdm import tqdm

from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import make_column_transformer , make_column_selector

from xgboost import XGBClassifier

from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")
import os 
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\human-resources-analytics')

# sklearn

## 1. Adaboost

## 2. Gradient Boosting on Breast Cancer

In [50]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Wisconsin')

In [51]:
cancer = pd.read_csv('BreastCancer.csv',index_col=0)
cancer

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,Benign
63375,9,1,2,6,4,10,7,7,2,Malignant
76389,10,4,7,2,2,8,6,1,1,Malignant
95719,6,10,10,10,8,10,7,10,7,Malignant
128059,1,1,1,1,2,5,5,1,1,Benign
...,...,...,...,...,...,...,...,...,...,...
1369821,10,10,10,10,5,10,10,10,7,Malignant
1371026,5,10,10,10,4,10,5,6,3,Malignant
1371920,5,1,1,1,2,1,3,2,1,Benign
8233704,4,1,1,1,1,1,2,1,1,Benign
13454352,1,1,3,1,2,1,2,1,1,Benign

In [52]:
X,y = cancer.drop('Class', axis = 1) , cancer['Class']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

In [53]:
gbm = GradientBoostingClassifier(random_state = 26)
gbm.fit(X_train, y_train)
y_pred = gbm.predict(X_test)
accuracy_score(y_test, y_pred)

0.9571428571428572

## 2. Gradient Boosting on HR_CSV

In [54]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\human-resources-analytics')
hr = pd.read_csv('HR_comma_sep.csv')
hr

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14990,0.40,0.57,2,151,3,0,1,0,support,low
14991,0.37,0.48,2,160,3,0,1,0,support,low
14992,0.37,0.53,2,143,3,0,1,0,support,low
14993,0.11,0.96,6,280,4,0,1,0,support,low
14994,0.37,0.52,2,158,3,0,1,0,support,low

In [55]:
X,y = hr.drop('left', axis = 1) , hr['left']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

In [56]:
ohe = OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')
ct = make_column_transformer(
    (ohe, make_column_selector(dtype_include=object)),
    ('passthrough', make_column_selector(dtype_include=['int64','float64'])),
    verbose_feature_names_out=False
).set_output(transform='pandas')

In [57]:
X_train_trans = ct.fit_transform(X_train) 
X_test_tans = ct.transform(X_test)

In [34]:
gbm = GradientBoostingClassifier(random_state = 26)
gbm.fit(X_train_trans, y_train)
y_pred = gbm.predict(X_test_tans)
accuracy_score(y_test, y_pred)

0.9755501222493888

In [23]:
learning_rate = np.linspace(0.01,0.9,10)
max_depth = [None,2,3,4]
n_estimator  = [25,50,100]

scores =  []
for l in tqdm(learning_rate):
    for d in max_depth:
        for n in n_estimator:
            
            gbm = GradientBoostingClassifier(random_state = 26, learning_rate=l, max_depth=d, n_estimators=n)
            gbm.fit(X_train_trans, y_train)
            y_pred = gbm.predict(X_test_tans) 

            scores.append([l, d, n ,accuracy_score(y_test, y_pred) ])
df_scores = pd.DataFrame(scores , columns=['learning_rate','max_depth','n_estimator','score'])
df_scores.sort_values(by='score' , ascending=False)

100%|██████████| 10/10 [02:03<00:00, 12.35s/it]

    learning_rate  max_depth  n_estimator     score
83       0.603333        4.0          100  0.987553
71       0.504444        4.0          100  0.985552
82       0.603333        4.0           50  0.983774
1        0.010000        NaN           50  0.983552
59       0.405556        4.0          100  0.983330
..            ...        ...          ...       ...
4        0.010000        2.0           50  0.762392
6        0.010000        3.0           25  0.762169
3        0.010000        2.0           25  0.762169
0        0.010000        NaN           25  0.762169
9        0.010000        4.0           25  0.762169

[120 rows x 4 columns]

In [28]:
# !pip install xgboost
#

# xgboost

## 1. XGBClassifier  from XGBoost

In [39]:
learning_rate = np.linspace(0.01,0.9,10)
max_depth = [None,2,3,4]
n_estimator  = [25,50,100]

scores =  []
for l in tqdm(learning_rate):
    for d in max_depth:
        for n in n_estimator:
            
            gbm = XGBClassifier(random_state = 26, learning_rate=l, max_depth=d, n_estimators=n)
            gbm.fit(X_train_trans, y_train)
            y_pred = gbm.predict(X_test_tans) 

            scores.append([l, d, n ,accuracy_score(y_test, y_pred) ])
df_scores = pd.DataFrame(scores , columns=['learning_rate','max_depth','n_estimator','score'])
df_scores.sort_values(by='score' , ascending=False)

100%|██████████| 10/10 [00:18<00:00,  1.82s/it]

    learning_rate  max_depth  n_estimator     score
62       0.504444        NaN          100  0.988220
38       0.306667        NaN          100  0.987997
73       0.603333        NaN           50  0.987775
85       0.702222        NaN           50  0.987775
86       0.702222        NaN          100  0.987553
..            ...        ...          ...       ...
4        0.010000        2.0           50  0.762392
6        0.010000        3.0           25  0.762169
3        0.010000        2.0           25  0.762169
0        0.010000        NaN           25  0.762169
9        0.010000        4.0           25  0.762169

[120 rows x 4 columns]

# LightGBM

## 2. LightGBM  from microsoft

In [48]:
# !pip install lightgbm

In [31]:
from lightgbm import LGBMClassifier

In [42]:
learning_rate = np.linspace(0.01,0.9,10)
max_depth = [None,2,3,4]
n_estimator  = [25,50,100]

scores =  []
for l in tqdm(learning_rate):
    for d in max_depth:
        for n in n_estimator:
            
            gbm = LGBMClassifier(random_state = 26, verbose = -1,learning_rate=l, max_depth=d, n_estimators=n)
            gbm.fit(X_train_trans, y_train)
            y_pred = gbm.predict(X_test_tans) 

            scores.append([l, d, n ,accuracy_score(y_test, y_pred) ])
df_scores = pd.DataFrame(scores , columns=['l_rate','n','depth','score'])
df_scores.sort_values(by='score' , ascending=False)

100%|██████████| 10/10 [00:05<00:00,  1.94it/s]

      l_rate    n  depth     score
37  0.306667  NaN     50  0.988664
26  0.207778  NaN    100  0.988664
50  0.405556  NaN    100  0.988442
38  0.306667  NaN    100  0.988442
61  0.504444  NaN     50  0.988442
..       ...  ...    ...       ...
4   0.010000  2.0     50  0.762392
6   0.010000  3.0     25  0.762169
3   0.010000  2.0     25  0.762169
0   0.010000  NaN     25  0.762169
9   0.010000  4.0     25  0.762169

[120 rows x 4 columns]

# CatBoost

## 3. CatBoost

In [47]:
# !pip install catboost

In [45]:
from catboost import CatBoostClassifier

In [46]:
learning_rate = np.linspace(0.01,0.9,10)
max_depth = [None,2,3,4]
n_estimator  = [25,50,100]

scores =  []
for l in tqdm(learning_rate):
    for d in max_depth:
        for n in n_estimator:
            
            gbm = CatBoostClassifier(random_state = 26, verbose = False,learning_rate=l, max_depth=d, n_estimators=n)
            gbm.fit(X_train_trans, y_train)
            y_pred = gbm.predict(X_test_tans) 

            scores.append([l, d, n ,accuracy_score(y_test, y_pred) ])
df_scores = pd.DataFrame(scores , columns=['l_rate','n','depth','score'])
df_scores.sort_values(by='score' , ascending=False)

100%|██████████| 10/10 [00:35<00:00,  3.52s/it]

       l_rate    n  depth     score
98   0.801111  NaN    100  0.981551
110  0.900000  NaN    100  0.980440
86   0.702222  NaN    100  0.979773
119  0.900000  4.0    100  0.979106
74   0.603333  NaN    100  0.978884
..        ...  ...    ...       ...
5    0.010000  2.0    100  0.907090
7    0.010000  3.0     50  0.906646
6    0.010000  3.0     25  0.901534
4    0.010000  2.0     50  0.856635
3    0.010000  2.0     25  0.855301

[120 rows x 4 columns]

Categorical Features

In [59]:
hr

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14990,0.40,0.57,2,151,3,0,1,0,support,low
14991,0.37,0.48,2,160,3,0,1,0,support,low
14992,0.37,0.53,2,143,3,0,1,0,support,low
14993,0.11,0.96,6,280,4,0,1,0,support,low
14994,0.37,0.52,2,158,3,0,1,0,support,low

In [69]:
categories = ['Department', 'salary']
gbm = CatBoostClassifier(random_state = 26, verbose = False ,cat_features=categories,learning_rate=l, max_depth=d, n_estimators=n)
gbm.fit(X_train, y_train)
y_pred = gbm.predict(X_test)
accuracy_score(y_test, y_pred)

0.975994665481218

In [68]:
learning_rate = np.linspace(0.01,0.9,10)
max_depth = [None,2,3,4]
n_estimator  = [25,50,100]

scores =  []
for l in tqdm(learning_rate):
    for d in max_depth:
        for n in n_estimator:
            
            gbm = CatBoostClassifier(random_state = 26, verbose = False ,cat_features=categories,learning_rate=l, max_depth=d, n_estimators=n)
            gbm.fit(X_train, y_train)
            y_pred = gbm.predict(X_test) 

            scores.append([l, d, n ,accuracy_score(y_test, y_pred) ])
df_scores = pd.DataFrame(scores , columns=['l_rate','n','depth','score'])
df_scores.sort_values(by='score' , ascending=False)

100%|██████████| 10/10 [02:29<00:00, 14.97s/it]

       l_rate    n  depth     score
110  0.900000  NaN    100  0.980885
98   0.801111  NaN    100  0.979773
86   0.702222  NaN    100  0.978662
97   0.801111  NaN     50  0.978440
107  0.801111  4.0    100  0.978217
..        ...  ...    ...       ...
15   0.108889  2.0     25  0.910202
5    0.010000  2.0    100  0.907090
6    0.010000  3.0     25  0.901978
4    0.010000  2.0     50  0.855301
3    0.010000  2.0     25  0.855301

[120 rows x 4 columns]

# All Boosting on Vehicle DATASET

In [77]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Vehicle Silhouettes')

In [82]:
Vehicle = pd.read_csv('Vehicle.csv',index_col=0)
Vehicle

,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
Comp,,,,,,,,,,,,,,,,,,
95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,39,87,183,64,8,169,40,20,134,200,422,149,72,7,25,188,195,saab
89,46,84,163,66,11,159,43,20,159,173,368,176,72,1,20,186,197,van
106,54,101,222,67,12,222,30,25,173,228,721,200,70,3,4,187,201,saab
86,36,78,146,58,7,135,50,18,124,155,270,148,66,0,25,190,195,saab
85,36,66,123,55,5,120,56,17,128,140,212,131,73,1,18,186,190,van

In [97]:
X,y = Vehicle.drop('Class', axis = 1) , Vehicle['Class']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

## 1. GradientBoostingClassifier

In [98]:


learning_rate = np.linspace(0.01,0.9,10)
max_depth = [None,2,3,4]
n_estimator  = [25,50,100]

scores =  []
for l in tqdm(learning_rate):
    for d in max_depth:
        for n in n_estimator:
            
            gbm = GradientBoostingClassifier(random_state = 26, verbose = False,learning_rate=l, max_depth=d, n_estimators=n)
            gbm.fit(X_train, y_train)
            y_pred = gbm.predict(X_test) 

            scores.append([l, d, n ,accuracy_score(y_test, y_pred) ])
df_scores = pd.DataFrame(scores , columns=['l_rate','n','depth','score'])
df_scores.sort_values(by='score' , ascending=False)

100%|██████████| 10/10 [01:40<00:00, 10.04s/it]

       l_rate    n  depth     score
101  0.801111  2.0    100  0.779528
53   0.405556  2.0    100  0.775591
65   0.504444  2.0    100  0.775591
115  0.900000  3.0     50  0.775591
64   0.504444  2.0     50  0.771654
..        ...  ...    ...       ...
14   0.108889  NaN    100  0.692913
25   0.207778  NaN     50  0.692913
13   0.108889  NaN     50  0.688976
24   0.207778  NaN     25  0.688976
12   0.108889  NaN     25  0.685039

[120 rows x 4 columns]

## 2.XGBClassifier

In [89]:
from sklearn.preprocessing import LabelEncoder

In [90]:
le = LabelEncoder()
le_y = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X,le_y, test_size = 0.3, random_state=26, stratify=y)

In [91]:
learning_rate = np.linspace(0.01,0.9,10)
max_depth = [None,2,3,4]
n_estimator  = [25,50,100]

scores =  []
for l in tqdm(learning_rate):
    for d in max_depth:
        for n in n_estimator:
            
            gbm = XGBClassifier(random_state = 26, learning_rate=l, max_depth=d, n_estimators=n)
            gbm.fit(X_train, y_train)
            y_pred = gbm.predict(X_test) 

            scores.append([l, d, n ,accuracy_score(y_test, y_pred) ])
df_scores = pd.DataFrame(scores , columns=['learning_rate','max_depth','n_estimator','score'])
df_scores.sort_values(by='score' , ascending=False)

100%|██████████| 10/10 [00:22<00:00,  2.26s/it]

     learning_rate  max_depth  n_estimator     score
100       0.801111        2.0           50  0.807087
112       0.900000        2.0           50  0.803150
101       0.801111        2.0          100  0.799213
89        0.702222        2.0          100  0.799213
105       0.801111        4.0           25  0.799213
..             ...        ...          ...       ...
7         0.010000        3.0           50  0.704724
4         0.010000        2.0           50  0.700787
1         0.010000        NaN           50  0.696850
6         0.010000        3.0           25  0.681102
3         0.010000        2.0           25  0.625984

[120 rows x 4 columns]

## 3.LGBMClassifier

In [92]:
learning_rate = np.linspace(0.01,0.9,10)
max_depth = [None,2,3,4]
n_estimator  = [25,50,100]

scores =  []
for l in tqdm(learning_rate):
    for d in max_depth:
        for n in n_estimator:
            
            gbm = LGBMClassifier(random_state = 26, verbose = -1,learning_rate=l, max_depth=d, n_estimators=n)
            gbm.fit(X_train, y_train)
            y_pred = gbm.predict(X_test) 

            scores.append([l, d, n ,accuracy_score(y_test, y_pred) ])
df_scores = pd.DataFrame(scores , columns=['l_rate','n','depth','score'])
df_scores.sort_values(by='score' , ascending=False)

100%|██████████| 10/10 [00:05<00:00,  1.76it/s]

       l_rate    n  depth     score
99   0.801111  2.0     25  0.803150
106  0.801111  4.0     50  0.803150
119  0.900000  4.0    100  0.803150
76   0.603333  2.0     50  0.803150
53   0.405556  2.0    100  0.799213
..        ...  ...    ...       ...
1    0.010000  NaN     50  0.692913
10   0.010000  4.0     50  0.692913
6    0.010000  3.0     25  0.692913
8    0.010000  3.0    100  0.685039
0    0.010000  NaN     25  0.681102

[120 rows x 4 columns]

## 4.CatBoostClassifier

In [93]:
learning_rate = np.linspace(0.01,0.9,10)
max_depth = [None,2,3,4]
n_estimator  = [25,50,100]

scores =  []
for l in tqdm(learning_rate):
    for d in max_depth:
        for n in n_estimator:
            
            gbm = CatBoostClassifier(random_state = 26, verbose = False,learning_rate=l, max_depth=d, n_estimators=n)
            gbm.fit(X_train, y_train)
            y_pred = gbm.predict(X_test) 

            scores.append([l, d, n ,accuracy_score(y_test, y_pred) ])
df_scores = pd.DataFrame(scores , columns=['l_rate','n','depth','score'])
df_scores.sort_values(by='score' , ascending=False)

100%|██████████| 10/10 [00:30<00:00,  3.09s/it]

      l_rate    n  depth     score
37  0.306667  NaN     50  0.787402
31  0.207778  3.0     50  0.787402
47  0.306667  4.0    100  0.779528
85  0.702222  NaN     50  0.775591
98  0.801111  NaN    100  0.775591
..       ...  ...    ...       ...
4   0.010000  2.0     50  0.665354
7   0.010000  3.0     50  0.665354
5   0.010000  2.0    100  0.661417
6   0.010000  3.0     25  0.661417
3   0.010000  2.0     25  0.641732

[120 rows x 4 columns]