In [1]:
import plotly.express as px
import pandas as pd

In [ ]:
df = px.data.tips()
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
fig = px.pie(df, names = 'day'  ,values= 'total_bill')
fig

In [8]:
fig = px.pie(df, names = 'day'  ,values= 'total_bill',hole = 0.5)
fig

In [10]:
fig = px.pie(df, names = 'day'  ,values= 'total_bill',hole = 0.5)
fig

fig.update_layout(
    title='Life expectancy over the years',
    xaxis_title='Country',
    yaxis_title = 'Life Expectancy', 
)

In [13]:
fig = px.pie(df, names = 'day'  ,values= 'total_bill',hole = 0.5, template = 'seaborn')
fig

fig.update_layout(
    title='Life expectancy over the years',
    xaxis_title='Country',
    yaxis_title = 'Life Expectancy', 
)

In [18]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
px.sunburst(df, path=['day','time','sex'], values='total_bill')

In [16]:
FIG = px.treemap(df, path=['day','time','sex'], values='total_bill')
FIG