In [83]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import os
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Wisconsin')

In [76]:
bcancer = pd.read_csv('BreastCancer.csv',index_col=0)
bcancer

          Clump  UniCell_Size  Uni_CellShape  MargAdh  SEpith  BareN  BChromatin  NoemN  Mitoses      Class
Code
61634         5             4              3        1       2      2           2      3        1     Benign
63375         9             1              2        6       4     10           7      7        2  Malignant
76389        10             4              7        2       2      8           6      1        1  Malignant
95719         6            10             10       10       8     10           7     10        7  Malignant
128059        1             1              1        1       2      5           5      1        1     Benign
...         ...           ...            ...      ...     ...    ...         ...    ...      ...        ...
1369821      10            10             10       10       5     10          10     10        7  Malignant
1371026       5            10             10       10       4     10           5      6        3  Malignant
1371920       5             1              1        1       2      1           3      2        1     Benign
8233704       4             1              1        1       1      1           2      1        1     Benign
13454352      1             1              3        1       2      1           2      1        1     Benign

[699 rows x 10 columns]

In [35]:
X , y = bcancer.drop('Class',axis = 1), bcancer['Class']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26)

In [36]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.9476190476190476

In [37]:
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.9047619047619048

In [38]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.9761904761904762

In [39]:
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.9523809523809523

### Find best accuracy_score

In [48]:
ks = range(1,15)
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train , y_train)
    y_pred = knn.predict(X_test)
    scores.append([k , accuracy_score(y_test , y_pred )])

df_scores = pd.DataFrame(scores, columns=['K','score'])
df_scores.sort_values('score', ascending=False)

     K     score
2    3  0.976190
4    5  0.971429
10  11  0.957143
12  13  0.957143
3    4  0.952381
5    6  0.952381
11  12  0.952381
8    9  0.952381
6    7  0.952381
7    8  0.952381
13  14  0.952381
0    1  0.947619
9   10  0.942857
1    2  0.904762

### Stratify

In [74]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Vehicle Silhouettes')
df = pd.read_csv('Vehicle.csv')

df
X , y = df.drop('Class' , axis = 1), df['Class']


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y) # startifification maintains ratio of class as original in testing set also

ks = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train , y_train)
    y_pred = knn.predict(X_test)
    scores.append([k , accuracy_score(y_test , y_pred )])

df_scores = pd.DataFrame(scores, columns=['K','score'])
df_scores.sort_values('score', ascending=False)

     K     score
0    1  0.677165
1    2  0.673228
4    5  0.661417
6    7  0.661417
2    3  0.657480
10  11  0.657480
7    8  0.657480
8    9  0.653543
5    6  0.653543
3    4  0.649606
9   10  0.649606
12  13  0.649606
13  14  0.629921
11  12  0.625984
14  15  0.618110

#### Using Standard Scaler

In [81]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Vehicle Silhouettes')
df = pd.read_csv('Vehicle.csv')

df
X , y = df.drop('Class' , axis = 1), df['Class']


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

scaler = StandardScaler().set_output(transform='pandas')
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


ks = range(1,15)
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled , y_train)
    y_pred = knn.predict(X_test_scaled)
    scores.append([k , accuracy_score(y_test , y_pred )])

df_scores = pd.DataFrame(scores, columns=['K','score'])
df_scores.sort_values('score', ascending=False)

     K     score
2    3  0.728346
5    6  0.724409
11  12  0.716535
13  14  0.712598
7    8  0.712598
12  13  0.712598
4    5  0.708661
3    4  0.704724
8    9  0.700787
9   10  0.700787
10  11  0.696850
6    7  0.692913
0    1  0.685039
1    2  0.673228

### KNN Algorithm : Using Pipeline (1. StandardScaler, 2. KNeighborsClassifier)

In [86]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Vehicle Silhouettes')
df = pd.read_csv('Vehicle.csv')

df
X , y = df.drop('Class' , axis = 1), df['Class']


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

scaler = StandardScaler().set_output(transform='pandas')

ks = range(1,15)
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    pipe = Pipeline([("Scale",scaler),("KNN", knn)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append([k , accuracy_score(y_test , y_pred )])

df_scores = pd.DataFrame(scores, columns=['K','score'])
df_scores.sort_values('score', ascending=False)

     K     score
2    3  0.728346
5    6  0.724409
11  12  0.716535
13  14  0.712598
7    8  0.712598
12  13  0.712598
4    5  0.708661
3    4  0.704724
8    9  0.700787
9   10  0.700787
10  11  0.696850
6    7  0.692913
0    1  0.685039
1    2  0.673228

#### Using Min Max Scaler

In [82]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Vehicle Silhouettes')
df = pd.read_csv('Vehicle.csv')

df
X , y = df.drop('Class' , axis = 1), df['Class']


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

scaler = MinMaxScaler().set_output(transform='pandas')
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


ks = range(1,15)
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled , y_train)
    y_pred = knn.predict(X_test_scaled)
    scores.append([k , accuracy_score(y_test , y_pred )])

df_scores = pd.DataFrame(scores, columns=['K','score'])
df_scores.sort_values('score', ascending=False)

     K     score
5    6  0.736220
4    5  0.712598
11  12  0.712598
3    4  0.700787
6    7  0.700787
13  14  0.700787
12  13  0.692913
7    8  0.692913
2    3  0.692913
8    9  0.688976
10  11  0.688976
9   10  0.685039
0    1  0.673228
1    2  0.669291

### KNN Algorithm : Using Min Max Scaler passing through pipeline

In [88]:
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Vehicle Silhouettes')
df = pd.read_csv('Vehicle.csv')

df
X , y = df.drop('Class' , axis = 1), df['Class']


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

min_max_scaler = MinMaxScaler().set_output(transform='pandas')

ks = range(1,15)
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    pipe = Pipeline([("Scale",min_max_scaler),("KNN", knn)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append([k , accuracy_score(y_test , y_pred )])

df_scores = pd.DataFrame(scores, columns=['K','score'])
df_scores.sort_values('score', ascending=False)

     K     score
5    6  0.736220
4    5  0.712598
11  12  0.712598
3    4  0.700787
6    7  0.700787
13  14  0.700787
12  13  0.692913
7    8  0.692913
2    3  0.692913
8    9  0.688976
10  11  0.688976
9   10  0.685039
0    1  0.673228
1    2  0.669291