In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis , QuadraticDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer , make_column_selector,make_column_transformer
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.pipeline import Pipeline, make_pipeline
import os
import warnings
warnings.filterwarnings('ignore')
os.chdir('E:\Backup Files Abhinav_Satyam\Practical Machine Learning\Sanjay Sir Git Repo\Datasets\Cases\Image_Segmentation')

In [23]:
imgseg = pd.read_csv('Image_Segmentation.csv')
imgseg

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.000000,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.000000,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.000000,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.000000,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.000000,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,GRASS,36,243,9,0.111111,0.0,1.888889,1.851851,2.000000,0.711110,13.333333,9.888889,12.111111,18.000000,-10.333333,-3.666667,14.000000,18.000000,0.452229,2.368311
205,GRASS,186,218,9,0.000000,0.0,1.166667,0.744444,1.166667,0.655555,13.703704,10.666667,12.666667,17.777779,-9.111111,-3.111111,12.222222,17.777779,0.401347,2.382684
206,GRASS,197,236,9,0.000000,0.0,2.444444,6.829628,3.333333,7.599998,16.074074,13.111111,16.666668,18.444445,-8.888889,1.777778,7.111111,18.555555,0.292729,2.789800
207,GRASS,208,240,9,0.111111,0.0,1.055556,0.862963,2.444444,5.007407,14.148149,10.888889,13.000000,18.555555,-9.777778,-3.444444,13.222222,18.555555,0.421621,2.392487
208,GRASS,223,185,9,0.000000,0.0,0.500000,0.349603,2.388889,2.080776,12.962963,11.555555,9.777778,17.555555,-4.222222,-9.555555,13.777778,17.555555,0.445418,1.838850

In [24]:
X, y = imgseg.drop('Class', axis = 1), imgseg['Class']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=26, stratify=y)

In [25]:
solvers=['lbfgs','newton-cg','newton-cholesky','sag','saga']
# liblinear   - not applied
scores  =[]


for s in solvers:
    lr  = LogisticRegression(solver=s)
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    scores.append([s , accuracy_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores , columns=['solver','score'])
df_scores

            solver     score
0            lbfgs  0.873016
1        newton-cg  0.920635
2  newton-cholesky  0.904762
3              sag  0.841270
4             saga  0.793651

In [28]:
solvers=['lbfgs','newton-cg','newton-cholesky','sag','saga']
# liblinear   - not applied
cs = np.linspace(0.001, 10,20)
scores  =[]


for s in solvers:
    for c in cs:
        lr  = LogisticRegression(solver=s,C = c)
        lr.fit(X_train, y_train)
        y_pred = lr.predict(X_test)
        scores.append([s , c, accuracy_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores , columns=['solver','c','score'])
df_scores.sort_values(by='score',ascending=False)

       solver          c     score
35  newton-cg   7.894947  0.920635
33  newton-cg   6.842421  0.920635
27  newton-cg   3.684842  0.920635
28  newton-cg   4.211105  0.920635
24  newton-cg   2.106053  0.920635
..        ...        ...       ...
95       saga   7.894947  0.793651
99       saga  10.000000  0.793651
97       saga   8.947474  0.793651
60        sag   0.001000  0.777778
80       saga   0.001000  0.777778

[100 rows x 3 columns]

# When l1_ratio = 1

In [31]:
 
# liblinear   - not applied
cs = np.linspace(0.001, 10,20)
scores  =[]

 
for c in cs:
    lr  = LogisticRegression(solver='saga',C = c,l1_ratio=1)
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    scores.append([ c, accuracy_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores , columns=['c','score'])
df_scores.sort_values(by='score',ascending=False)

            c     score
1    0.527263  0.793651
2    1.053526  0.793651
3    1.579789  0.793651
4    2.106053  0.793651
12   6.316158  0.793651
5    2.632316  0.793651
6    3.158579  0.793651
7    3.684842  0.793651
8    4.211105  0.793651
9    4.737368  0.793651
10   5.263632  0.793651
11   5.789895  0.793651
16   8.421211  0.793651
13   6.842421  0.793651
14   7.368684  0.793651
15   7.894947  0.793651
18   9.473737  0.793651
17   8.947474  0.793651
19  10.000000  0.793651
0    0.001000  0.285714

# POYNOMIAL