In [1]:
import pandas as pd
import numpy as np

In [2]:
people = {
    'first': ['ram', np.nan, 'amit', None, 'priya', 'rohan', np.nan, 'sneha', 'vikram', None],
    'last': ['p', 'n', None, 'kumar', 'sharma', np.nan, 'verma', 'patel', None, 'singh'],
    'email': ['shib@12', None, 'amit@123', 'john@gmail.com', np.nan, 'rohan@yahoo.com', 'sneha@work.com', None, 'vik@test.com', 'admin@mail.com'],
    'age': [22, 22, np.nan, 25, 30, 28, None, 22, 35, 40]
}

df = pd.DataFrame(people)

In [3]:
df

    first    last            email   age
0     ram       p          shib@12  22.0
1     NaN       n              NaN  22.0
2    amit     NaN         amit@123   NaN
3     NaN   kumar   john@gmail.com  25.0
4   priya  sharma              NaN  30.0
5   rohan     NaN  rohan@yahoo.com  28.0
6     NaN   verma   sneha@work.com   NaN
7   sneha   patel              NaN  22.0
8  vikram     NaN     vik@test.com  35.0
9     NaN   singh   admin@mail.com  40.0

In [4]:
df.fillna(1)

    first    last            email   age
0     ram       p          shib@12  22.0
1       1       n                1  22.0
2    amit       1         amit@123   1.0
3       1   kumar   john@gmail.com  25.0
4   priya  sharma                1  30.0
5   rohan       1  rohan@yahoo.com  28.0
6       1   verma   sneha@work.com   1.0
7   sneha   patel                1  22.0
8  vikram       1     vik@test.com  35.0
9       1   singh   admin@mail.com  40.0

In [5]:
df.dropna()

  first last    email   age
0   ram    p  shib@12  22.0

In [6]:
df.dropna(how='all')

    first    last            email   age
0     ram       p          shib@12  22.0
1     NaN       n              NaN  22.0
2    amit     NaN         amit@123   NaN
3     NaN   kumar   john@gmail.com  25.0
4   priya  sharma              NaN  30.0
5   rohan     NaN  rohan@yahoo.com  28.0
6     NaN   verma   sneha@work.com   NaN
7   sneha   patel              NaN  22.0
8  vikram     NaN     vik@test.com  35.0
9     NaN   singh   admin@mail.com  40.0

In [7]:
df.dropna(subset=['age'])

    first    last            email   age
0     ram       p          shib@12  22.0
1     NaN       n              NaN  22.0
3     NaN   kumar   john@gmail.com  25.0
4   priya  sharma              NaN  30.0
5   rohan     NaN  rohan@yahoo.com  28.0
7   sneha   patel              NaN  22.0
8  vikram     NaN     vik@test.com  35.0
9     NaN   singh   admin@mail.com  40.0

In [8]:
df.fillna({'email':'test','age':0})

    first    last            email   age
0     ram       p          shib@12  22.0
1     NaN       n             test  22.0
2    amit     NaN         amit@123   0.0
3     NaN   kumar   john@gmail.com  25.0
4   priya  sharma             test  30.0
5   rohan     NaN  rohan@yahoo.com  28.0
6     NaN   verma   sneha@work.com   0.0
7   sneha   patel             test  22.0
8  vikram     NaN     vik@test.com  35.0
9     NaN   singh   admin@mail.com  40.0