In [1]:
import pandas as pd
import numpy as np

In [11]:
df= pd.read_csv('Data.tsv' , delimiter = '\t')

In [14]:
df=pd.read_csv('survey_results.csv')
df

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89179,89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89180,89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89181,89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89182,89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89183,89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [5]:
df

,Name,Position,Office,Age,Start date,Salary
0,Airi Satou,Accountant,Tokyo,33,2008-11-28,"$162,700"
1,Angelica Ramos,Chief Executive Officer (CEO),London,47,2009-10-09,"$1,200,000"
2,Ashton Cox,Junior Technical Author,San Francisco,66,2009-01-12,"$86,000"
3,Bradley Greer,Software Engineer,London,41,2012-10-13,"$132,000"
4,Brenden Wagner,Software Engineer,San Francisco,28,2011-06-07,"$206,850"
5,Brielle Williamson,Integration Specialist,New York,61,2012-12-02,"$372,000"
6,Bruno Nash,Software Engineer,London,38,2011-05-03,"$163,500"
7,Caesar Vance,Pre-Sales Support,New York,21,2011-12-12,"$106,450"
8,Cara Stevens,Sales Assistant,New York,46,2011-12-06,"$145,600"
9,Cedric Kelly,Senior Javascript Developer,Edinburgh,22,2012-03-29,"$433,060"
10,Charde Marshall,Regional Director,San Francisco,36,2008-10-16,"$470,600"
11,Colleen Hurst,Javascript Developer,San Francisco,39,2009-09-15,"$205,500"
12,Dai Rios,Personnel Lead,Edinburgh,35,2012-09-26,"$217,500"
13,Donna Snider,Customer Support,New York,27,2011-01-25,"$112,000"
14,Doris Wilder,Sales Assistant,Sydney,23,2010-09-20,"$85,600"
15,Finn Camacho,Support Engineer,San Francisco,47,2009-07-07,"$87,500"
16,Fiona Green,Chief Operating Officer (COO),San Francisco,48,2010-03-11,"$850,000"
17,Garrett Winters,Accountant,Tokyo,63,2011-07-25,"$170,750"
18,Gavin Cortez,Team Leader,San Francisco,22,2008-10-26,"$235,500"
19,Gavin Joyce,Developer,Edinburgh,42,2010-12-22,"$92,575"
20,Gloria Little,Systems Administrator,New York,59,2009-04-10,"$237,500"
21,Haley Kennedy,Senior Marketing Designer,London,43,2012-12-18,"$313,500"
22,Hermione Butler,Regional Director,London,47,2011-03-21,"$356,250"
23,Herrod Chandler,Sales Assistant,San Francisco,59,2012-08-06,"$137,500"
24,Hope Fuentes,Secretary,San Francisco,41,2010-02-12,"$109,850"
25,Howard Hatfield,Office Manager,San Francisco,51,2008-12-16,"$164,500"
26,Jackson Bradshaw,Director,New York,65,2008-09-26,"$645,750"
27,Jena Gaines,Office Manager,London,30,2008-12-19,"$90,560"
28,Jenette Caldwell,Development Lead,New York,30,2011-09-03,"$345,000"
29,Jennifer Acosta,Junior Javascript Developer,Edinburgh,43,2013-02-01,"$75,650"
30,Jennifer Chang,Regional Director,Singapore,28,2010-11-14,"$357,650"
31,Jonas Alexander,Developer,San Francisco,30,2010-07-14,"$86,500"
32,Lael Greer,Systems Administrator,London,21,2009-02-27,"$103,500"
33,Martena Mccray,Post-Sales support,Edinburgh,46,2011-03-09,"$324,050"
34,Michael Bruce,Javascript Developer,Singapore,29,2011-06-27,"$183,000"
35,Michael Silva,Marketing Designer,London,66,2012-11-27,"$198,500"
36,Michelle House,Integration Specialist,Sydney,37,2011-06-02,"$95,400"
37,Olivia Liang,Support Engineer,Singapore,64,2011-02-03,"$234,500"
38,Paul Byrd,Chief Financial Officer (CFO),New York,64,2010-06-09,"$725,000"
39,Prescott Bartlett,Technical Author,London,27,2011-05-07,"$145,000"
40,Quinn Flynn,Support Lead,Edinburgh,22,2013-03-03,"$342,000"
41,Rhona Davidson,Integration Specialist,Tokyo,55,2010-10-14,"$327,900"
42,Sakura Yamamoto,Support Engineer,Tokyo,37,2009-08-19,"$139,575"
43,Serge Baldwin,Data Coordinator,Singapore,64,2012-04-09,"$138,575"
44,Shad Decker,Regional Director,Edinburgh,51,2008-11-13,"$183,000"
45,Shou Itou,Regional Marketing,Tokyo,20,2011-08-14,"$163,000"
46,Sonya Frost,Software Engineer,Edinburgh,23,2008-12-13,"$103,600"
47,Suki Burks,Developer,London,53,2009-10-22,"$114,500"
48,Tatyana Fitzpatrick,Regional Director,London,19,2010-03-17,"$385,750"
49,Thor Walton,Developer,New York,61,2013-08-11,"$98,540"
50,Tiger Nixon,System Architect,Edinburgh,61,2011-04-25,"$320,800"
51,Timothy Mooney,Office Manager,London,37,2008-12-11,"$136,200"
52,Unity Butler,Marketing Designer,San Francisco,47,2009-12-09,"$85,675"
53,Vivian Harrell,Financial Controller,San Francisco,62,2009-02-14,"$452,500"
54,Yuri Berry,Chief Marketing Officer (CMO),New York,40,2009-06-25,"$675,000"
55,Zenaida Frank,Software Engineer,New York,63,2010-01-04,"$125,250"
56,Zorita Serrano,Software Engineer,San Francisco,56,2012-06-01,"$115,000"
57,Name,Position,Office,Age,Start date,Salary

In [8]:
df.tail()

,Name,Position,Office,Age,Start date,Salary
53,Vivian Harrell,Financial Controller,San Francisco,62,2009-02-14,"$452,500"
54,Yuri Berry,Chief Marketing Officer (CMO),New York,40,2009-06-25,"$675,000"
55,Zenaida Frank,Software Engineer,New York,63,2010-01-04,"$125,250"
56,Zorita Serrano,Software Engineer,San Francisco,56,2012-06-01,"$115,000"
57,Name,Position,Office,Age,Start date,Salary

In [15]:
df.columns

Index(['ResponseId', 'Q120', 'MainBranch', 'Age', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'TechList', 'BuyNewTool', 'Country',
       'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysPersonal use',
       'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith',
       'OfficeStackAsyncWantToWorkWith', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'AISearchHaveWorkedWith',
       'AISearchWantToWorkWith', 'AIDevHaveWorkedWith', 'AIDevWantToWorkWith',
       'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOComm',
       'SOAI', 'AISelect', 'AISent', 'AIAcc', 'AIBen',
       'AIToolInterested in Using', 'AIToolCurrently Using',
       'AIToolNot interested in Using', 'AINextVery different',
       'AINextNeither different nor similar', 'AINextSomewhat similar',
       'AINextVery similar', 'AINextSomewhat different', 'TBranch', 'ICorPM',
       'WorkExp', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Knowledge_8',
       'Frequency_1', 'Frequency_2', 'Frequency_3', 'TimeSearching',
       'TimeAnswering', 'ProfessionalTech', 'Industry', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='str')

In [16]:
df.head(10)

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
5,6,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;Colleague;Online Course...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,30-60 minutes a day,15-30 minutes a day,DevOps function;Microservices;Observability to...,Other,Appropriate in length,Neither easy nor difficult,96828.0
6,7,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Profe...,Some college/university study without earning ...,Friend or family member;Online Courses or Cert...,NaN,...,1-2 times a week,3-5 times a week,1-2 times a week,Less than 15 minutes a day,15-30 minutes a day,Microservices;Automated testing;Continuous int...,"Information Services, IT, Software Development...",Appropriate in length,Easy,135000.0
7,8,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,60-120 minutes a day,30-60 minutes a day,None of these,Financial Services,NaN,NaN,80000.0
8,9,I agree,"I am not primarily a developer, but I write co...",45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Online Courses or Certification;On the job tra...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,64254.0
9,10,I agree,I am a developer by profession,25-34 years old,"Not employed, but looking for work",NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN

In [18]:
df.tail()

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
89179,89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89180,89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89181,89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89182,89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89183,89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 89184 entries, 0 to 89183
Data columns (total 84 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ResponseId                           89184 non-null  int64
 1   Q120                                 89184 non-null  str
 2   MainBranch                           89184 non-null  str
 3   Age                                  89184 non-null  str
 4   Employment                           87898 non-null  str
 5   RemoteWork                           73810 non-null  str
 6   CodingActivities                     73764 non-null  str
 7   EdLevel                              87973 non-null  str
 8   LearnCode                            87663 non-null  str
 9   LearnCodeOnline                      70084 non-null  str
 10  LearnCodeCoursesCert                 37076 non-null  str
 11  YearsCode                            87435 non-null  str
 12  YearsCodePro                         66136 non-null  str
 13  DevType                              76872 non-null  str
 14  OrgSize                              65043 non-null  str
 15  PurchaseInfluence                    64964 non-null  str
 16  TechList                             60851 non-null  str
 17  BuyNewTool                           83009 non-null  str
 18  Country                              87973 non-null  str
 19  Currency                             65334 non-null  str
 20  CompTotal                            48225 non-null  float64
 21  LanguageHaveWorkedWith               87140 non-null  str
 22  LanguageWantToWorkWith               80709 non-null  str
 23  DatabaseHaveWorkedWith               73435 non-null  str
 24  DatabaseWantToWorkWith               60911 non-null  str
 25  PlatformHaveWorkedWith               63628 non-null  str
 26  PlatformWantToWorkWith               51308 non-null  str
 27  WebframeHaveWorkedWith               66938 non-null  str
 28  WebframeWantToWorkWith               56741 non-null  str
 29  MiscTechHaveWorkedWith               57019 non-null  str
 30  MiscTechWantToWorkWith               46848 non-null  str
 31  ToolsTechHaveWorkedWith              77884 non-null  str
 32  ToolsTechWantToWorkWith              68315 non-null  str
 33  NEWCollabToolsHaveWorkedWith         85864 non-null  str
 34  NEWCollabToolsWantToWorkWith         76649 non-null  str
 35  OpSysPersonal use                    86557 non-null  str
 36  OpSysProfessional use                78587 non-null  str
 37  OfficeStackAsyncHaveWorkedWith       69090 non-null  str
 38  OfficeStackAsyncWantToWorkWith       53743 non-null  str
 39  OfficeStackSyncHaveWorkedWith        83439 non-null  str
 40  OfficeStackSyncWantToWorkWith        69776 non-null  str
 41  AISearchHaveWorkedWith               56328 non-null  str
 42  AISearchWantToWorkWith               46150 non-null  str
 43  AIDevHaveWorkedWith                  25904 non-null  str
 44  AIDevWantToWorkWith                  19587 non-null  str
 45  NEWSOSites                           87973 non-null  str
 46  SOVisitFreq                          87140 non-null  str
 47  SOAccount                            87852 non-null  str
 48  SOPartFreq                           66061 non-null  str
 49  SOComm                               87692 non-null  str
 50  SOAI                                 47858 non-null  str
 51  AISelect                             87973 non-null  str
 52  AISent                               61501 non-null  str
 53  AIAcc                                38594 non-null  str
 54  AIBen                                61396 non-null  str
 55  AIToolInterested in Using            32783 non-null  str
 56  AIToolCurrently Using                36137 non-null  str
 57  AIToolNot interested in Using        21069 non-null  str
 58  AINextVery different                 12661 non-null  str
 59  AINextNeither different nor similar  6599 non-null   str
 60  AINextSomewhat similar               6238 non-null   str
 61  AINextVery similar                   2621 non-null   str
 62  AINextSomewhat different             23303 non-null  str
 63  TBranch                              65768 non-null  str
 64  ICorPM                               43668 non-null  str
 65  WorkExp                              43579 non-null  float64
 66  Knowledge_1                          42535 non-null  str
 67  Knowledge_2                          41670 non-null  str
 68  Knowledge_3                          41798 non-null  str
 69  Knowledge_4                          41684 non-null  str
 70  Knowledge_5                          41527 non-null  str
 71  Knowledge_6                          41520 non-null  str
 72  Knowledge_7                          41467 non-null  str
 73  Knowledge_8                          41404 non-null  str
 74  Frequency_1                          41916 non-null  str
 75  Frequency_2                          41925 non-null  str
 76  Frequency_3                          41054 non-null  str
 77  TimeSearching                        42778 non-null  str
 78  TimeAnswering                        42629 non-null  str
 79  ProfessionalTech                     41783 non-null  str
 80  Industry                             36774 non-null  str
 81  SurveyLength                         86485 non-null  str
 82  SurveyEase                           86554 non-null  str
 83  ConvertedCompYearly                  48019 non-null  float64
dtypes: float64(3), int64(1), str(80)
memory usage: 195.6 MB

In [20]:
df.describe()

         ResponseId     CompTotal       WorkExp  ConvertedCompYearly
count  89184.000000  4.822500e+04  43579.000000         4.801900e+04
mean   44592.500000  1.036807e+42     11.405126         1.031101e+05
std    25745.347541  2.276847e+44      9.051989         6.814188e+05
min        1.000000  0.000000e+00      0.000000         1.000000e+00
25%    22296.750000  6.300000e+04      5.000000         4.390700e+04
50%    44592.500000  1.150000e+05      9.000000         7.496300e+04
75%    66888.250000  2.300000e+05     16.000000         1.216410e+05
max    89184.000000  5.000000e+46     50.000000         7.435143e+07

In [21]:
df.describe().map(lambda x: f'{x: .0f}')

,ResponseId,CompTotal,WorkExp,ConvertedCompYearly
count,89184,48225,43579,48019
mean,44592,1036806635562467391394372602402550216392704,11,103110
std,25745,227684720124393422298755801637800141977026560,9,681419
min,1,0,0,1
25%,22297,63000,5,43907
50%,44592,115000,9,74963
75%,66888,230000,16,121641
max,89184,49999999999999992051087350427974655758076739584,50,74351432

In [23]:
df = pd.read_csv('Data.tsv', delimiter = '\t')
df

,Name,Position,Office,Age,Start date,Salary
0,Airi Satou,Accountant,Tokyo,33,2008-11-28,"$162,700"
1,Angelica Ramos,Chief Executive Officer (CEO),London,47,2009-10-09,"$1,200,000"
2,Ashton Cox,Junior Technical Author,San Francisco,66,2009-01-12,"$86,000"
3,Bradley Greer,Software Engineer,London,41,2012-10-13,"$132,000"
4,Brenden Wagner,Software Engineer,San Francisco,28,2011-06-07,"$206,850"
5,Brielle Williamson,Integration Specialist,New York,61,2012-12-02,"$372,000"
6,Bruno Nash,Software Engineer,London,38,2011-05-03,"$163,500"
7,Caesar Vance,Pre-Sales Support,New York,21,2011-12-12,"$106,450"
8,Cara Stevens,Sales Assistant,New York,46,2011-12-06,"$145,600"
9,Cedric Kelly,Senior Javascript Developer,Edinburgh,22,2012-03-29,"$433,060"
10,Charde Marshall,Regional Director,San Francisco,36,2008-10-16,"$470,600"
11,Colleen Hurst,Javascript Developer,San Francisco,39,2009-09-15,"$205,500"
12,Dai Rios,Personnel Lead,Edinburgh,35,2012-09-26,"$217,500"
13,Donna Snider,Customer Support,New York,27,2011-01-25,"$112,000"
14,Doris Wilder,Sales Assistant,Sydney,23,2010-09-20,"$85,600"
15,Finn Camacho,Support Engineer,San Francisco,47,2009-07-07,"$87,500"
16,Fiona Green,Chief Operating Officer (COO),San Francisco,48,2010-03-11,"$850,000"
17,Garrett Winters,Accountant,Tokyo,63,2011-07-25,"$170,750"
18,Gavin Cortez,Team Leader,San Francisco,22,2008-10-26,"$235,500"
19,Gavin Joyce,Developer,Edinburgh,42,2010-12-22,"$92,575"
20,Gloria Little,Systems Administrator,New York,59,2009-04-10,"$237,500"
21,Haley Kennedy,Senior Marketing Designer,London,43,2012-12-18,"$313,500"
22,Hermione Butler,Regional Director,London,47,2011-03-21,"$356,250"
23,Herrod Chandler,Sales Assistant,San Francisco,59,2012-08-06,"$137,500"
24,Hope Fuentes,Secretary,San Francisco,41,2010-02-12,"$109,850"
25,Howard Hatfield,Office Manager,San Francisco,51,2008-12-16,"$164,500"
26,Jackson Bradshaw,Director,New York,65,2008-09-26,"$645,750"
27,Jena Gaines,Office Manager,London,30,2008-12-19,"$90,560"
28,Jenette Caldwell,Development Lead,New York,30,2011-09-03,"$345,000"
29,Jennifer Acosta,Junior Javascript Developer,Edinburgh,43,2013-02-01,"$75,650"
30,Jennifer Chang,Regional Director,Singapore,28,2010-11-14,"$357,650"
31,Jonas Alexander,Developer,San Francisco,30,2010-07-14,"$86,500"
32,Lael Greer,Systems Administrator,London,21,2009-02-27,"$103,500"
33,Martena Mccray,Post-Sales support,Edinburgh,46,2011-03-09,"$324,050"
34,Michael Bruce,Javascript Developer,Singapore,29,2011-06-27,"$183,000"
35,Michael Silva,Marketing Designer,London,66,2012-11-27,"$198,500"
36,Michelle House,Integration Specialist,Sydney,37,2011-06-02,"$95,400"
37,Olivia Liang,Support Engineer,Singapore,64,2011-02-03,"$234,500"
38,Paul Byrd,Chief Financial Officer (CFO),New York,64,2010-06-09,"$725,000"
39,Prescott Bartlett,Technical Author,London,27,2011-05-07,"$145,000"
40,Quinn Flynn,Support Lead,Edinburgh,22,2013-03-03,"$342,000"
41,Rhona Davidson,Integration Specialist,Tokyo,55,2010-10-14,"$327,900"
42,Sakura Yamamoto,Support Engineer,Tokyo,37,2009-08-19,"$139,575"
43,Serge Baldwin,Data Coordinator,Singapore,64,2012-04-09,"$138,575"
44,Shad Decker,Regional Director,Edinburgh,51,2008-11-13,"$183,000"
45,Shou Itou,Regional Marketing,Tokyo,20,2011-08-14,"$163,000"
46,Sonya Frost,Software Engineer,Edinburgh,23,2008-12-13,"$103,600"
47,Suki Burks,Developer,London,53,2009-10-22,"$114,500"
48,Tatyana Fitzpatrick,Regional Director,London,19,2010-03-17,"$385,750"
49,Thor Walton,Developer,New York,61,2013-08-11,"$98,540"
50,Tiger Nixon,System Architect,Edinburgh,61,2011-04-25,"$320,800"
51,Timothy Mooney,Office Manager,London,37,2008-12-11,"$136,200"
52,Unity Butler,Marketing Designer,San Francisco,47,2009-12-09,"$85,675"
53,Vivian Harrell,Financial Controller,San Francisco,62,2009-02-14,"$452,500"
54,Yuri Berry,Chief Marketing Officer (CMO),New York,40,2009-06-25,"$675,000"
55,Zenaida Frank,Software Engineer,New York,63,2010-01-04,"$125,250"
56,Zorita Serrano,Software Engineer,San Francisco,56,2012-06-01,"$115,000"
57,Name,Position,Office,Age,Start date,Salary

In [24]:
df = pd.read_csv('Transaction.txt', sep = '|')

In [25]:
df

,TransactionID,Date,CustomerType,ProductCategory,Quantity,Price,StoreLocation,PaymentMethod
0,TXN1001,2026-06-01,Member,Electronics,1,599.99,New York,Credit Card
1,TXN1002,2026-06-01,Normal,Clothing,3,25.50,Los Angeles,Cash
2,TXN1003,2026-06-02,Member,Home Goods,2,45.00,Chicago,Mobile Wallet
3,TXN1004,2026-06-02,Normal,Electronics,1,120.00,New York,Credit Card
4,TXN1005,2026-06-03,Member,Clothing,2,89.99,Chicago,Credit Card
5,TXN1006,2026-06-03,Normal,Books,4,12.99,Los Angeles,Cash

In [33]:
df = pd.read_excel('Financial Sample.xlsx')
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15,32670.0,0.00,32670.00,21780.0,10890.00,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,NaN,888.0,3,15,13320.0,0.00,13320.00,8880.0,4440.00,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15,37050.0,0.00,37050.00,24700.0,12350.00,2014-06-01,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,260,300,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,260,300,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,October,2014
697,Government,Mexico,Montana,High,1368.0,5,7,9576.0,1436.40,8139.60,6840.0,1299.60,2014-02-01,2,February,2014
698,Government,Canada,Paseo,High,723.0,10,7,5061.0,759.15,4301.85,3615.0,686.85,2014-04-01,4,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,250,12,21672.0,3250.80,18421.20,5418.0,13003.20,2014-05-01,5,May,2014

In [34]:
df.to_excel('Financial Sample2.xlsx')