In [3]:
import pandas as pd
import numpy as np

In [4]:
arr = np.array([10,20,30,40,50])
series = pd.Series(arr)
series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
names = ['Akshay','Amol','Aryan']
series = pd.Series(names)
series

0    Akshay
1      Amol
2     Aryan
dtype: object

In [9]:
head = pd.Series({'India':'Delhi',"Uk":"London","America":"New York","France":"Paris"})
head

India         Delhi
Uk           London
America    New York
France        Paris
dtype: object

In [10]:
head.index

Index(['India', 'Uk', 'America', 'France'], dtype='object')

In [11]:
head.values

array(['Delhi', 'London', 'New York', 'Paris'], dtype=object)

In [12]:
head.value_counts

<bound method IndexOpsMixin.value_counts of India         Delhi
Uk           London
America    New York
France        Paris
dtype: object>

In [13]:
head.loc['India']

'Delhi'

In [15]:
head.iloc[2]

'New York'

In [18]:
head['India':'America']

India         Delhi
Uk           London
America    New York
dtype: object

In [23]:
head[1:4]

Uk           London
America    New York
France        Paris
dtype: object

In [47]:
count = pd.Series({'America':30,'India':75,'France':15,'Uk':69})

In [48]:
count

America    [30, 40, 50]
India      [75, 65, 55]
France     [15, 25, 35]
Uk         [69, 59, 49]
dtype: object

In [42]:
df = pd.DataFrame({'Head Office':head,'Count':count})
df

        Head Office  Count
America    New York     30
France        Paris     15
India         Delhi     75
Uk           London     69

In [ ]:
df = pd.DataFrame({
    'Name': ['Akshay',"Amol",'aryan','ayush'],
    'Age' : [33,28,40,39],
    'City': ['Pune','Pune','Delhi','Delhi']

})  
df

     Name  Age   City
0  Akshay   33   Pune
1    Amol   28   Pune
2   aryan   40  Delhi
3   ayush   39  Delhi

In [51]:
df  = pd.DataFrame(data = [[500,15,40],[400,12,30],
                           [250,13,15],[300,14,15]],
                   index = ['Tata','Maruti','Hyundai','Honda'],
                   columns = ['Total Sale','Profit %','Market Share'])
df

         Total Sale  Profit %  Market Share
Tata            500        15            40
Maruti          400        12            30
Hyundai         250        13            15
Honda           300        14            15

In [53]:
df.loc['Tata']

Total Sale      500
Profit %         15
Market Share     40
Name: Tata, dtype: int64

In [56]:
df.iloc[-2]

Total Sale      250
Profit %         13
Market Share     15
Name: Hyundai, dtype: int64

In [54]:
df.iloc[3]

Total Sale      300
Profit %         14
Market Share     15
Name: Honda, dtype: int64

In [62]:
df['Tata':'Hyundai']

         Total Sale  Profit %  Market Share
Tata            500        15            40
Maruti          400        12            30
Hyundai         250        13            15

In [63]:
df.loc['Tata':'Hyundai','Profit %']

Tata       15
Maruti     12
Hyundai    13
Name: Profit %, dtype: int64

In [64]:
df.iloc[1:3,1:2]

         Profit %
Maruti         12
Hyundai        13

In [65]:
df.iloc[1:3,2]

Maruti     30
Hyundai    15
Name: Market Share, dtype: int64