In [17]:
import pandas as pd

In [25]:
data = {
    'name': ['Zoya Akhtar', 'Rahul Sharma', 'Emily Watson', 'Karan Patel','Karan Patel'],
    'email': ['zoya@example.com', 'rahul@example.com', 'emily@example.com', 'karan@example.com','df'],
    'salary': [92000, 78000, 105000, 64000,550000]
}
df = pd.DataFrame(data)

In [19]:
df

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000

In [28]:
df.nsmallest(2,'salary')

           name              email  salary
3   Karan Patel  karan@example.com   64000
1  Rahul Sharma  rahul@example.com   78000

In [20]:
df.nlargest(2,'salary')

           name              email  salary
2  Emily Watson  emily@example.com  105000
0   Zoya Akhtar   zoya@example.com   92000

In [22]:
df.sort_index(ascending=False)

           name              email  salary
3   Karan Patel  karan@example.com   64000
2  Emily Watson  emily@example.com  105000
1  Rahul Sharma  rahul@example.com   78000
0   Zoya Akhtar   zoya@example.com   92000

In [30]:
df.sort_index()

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000

In [21]:
df.sort_values(by='name')

           name              email  salary
2  Emily Watson  emily@example.com  105000
3   Karan Patel  karan@example.com   64000
1  Rahul Sharma  rahul@example.com   78000
0   Zoya Akhtar   zoya@example.com   92000

In [26]:
df.sort_values(by=['name','salary'],ascending=[False,True])

           name              email  salary
0   Zoya Akhtar   zoya@example.com   92000
1  Rahul Sharma  rahul@example.com   78000
3   Karan Patel  karan@example.com   64000
4   Karan Patel                 df  550000
2  Emily Watson  emily@example.com  105000