In [69]:
import numpy as np
import pandas as pd

Q1. Create a DataFrame containing student information like Name, Age, Department, %Marks

a.	Display column names of the DF

b.	Show min/max and average marks

c.	Get unique values and student count for each Department

In [70]:
data = {
    'Name': ['Alice Smith', 'Bob Jones', 'Charlie Brown', 'Diana Prince', 'Ethan Hunt', 'Fiona Gallagher'],
    'Age': [21, 22, 20, 23, 21, 22],
    'Department': ['Computer Science', 'Mathematics', 'Physics', 'Biology', 'Chemistry', 'Computer Science'],
    '% Marks': [88.5, 76.0, 92.3, 81.5, 95.0, 79.4]
}

In [71]:
df = pd.DataFrame(data=data)
df

              Name  Age        Department  % Marks
0      Alice Smith   21  Computer Science     88.5
1        Bob Jones   22       Mathematics     76.0
2    Charlie Brown   20           Physics     92.3
3     Diana Prince   23           Biology     81.5
4       Ethan Hunt   21         Chemistry     95.0
5  Fiona Gallagher   22  Computer Science     79.4

In [72]:
df.columns

Index(['Name', 'Age', 'Department', '% Marks'], dtype='str')

In [73]:
df['% Marks'].min()

np.float64(76.0)

In [74]:
df['% Marks'].max()

np.float64(95.0)

In [75]:
df['% Marks'].mean()

np.float64(85.45)

In [76]:
df.groupby(['Department']).count()['Name']

Department
Biology             1
Chemistry           1
Computer Science    2
Mathematics         1
Physics             1
Name: Name, dtype: int64

In [77]:
df['Department'].value_counts()

Department
Computer Science    2
Mathematics         1
Physics             1
Biology             1
Chemistry           1
Name: count, dtype: int64

In [78]:
df['Department'].unique()

<ArrowStringArray>
['Computer Science', 'Mathematics', 'Physics', 'Biology', 'Chemistry']
Length: 5, dtype: str

Q2. Read csv file solar.csv

a.	Display all the plants with capacity > 500 MW

b.	Display plant details for New York plant

c.	For all the plants display Average MW Per Plant and Generation (GWh)

d.	Sort the plants by Generation (GWh) (ascending) and Installed Capacity (MW)(descending)

e.	List top 5 plants for their Generation

f.	Display all plant details for states – California, Nevada, Arizona and Texas

g.	Group the plants by region, find – min/max capacity plant for each group

h.	Add following information to the existing details for the plants

	North Carolina	148	669	4.5	1162	North

In [79]:
df = pd.read_csv('solar.csv')
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

In [80]:
df[df['Installed Capacity (MW)'] > 500]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
7,Florida,15,535,12.3,453,South

In [81]:
df.iloc[6]

State                      New York
Number of Solar Plants           13
Installed Capacity (MW)          53
Average MW Per Plant            4.1
Generation (GWh)                 84
Region                         East
Name: 6, dtype: object

In [82]:
df[df['State'] == 'New York']

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East

In [83]:
df.query("State == 'New York'")

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East

In [84]:
df[['State','Average MW Per Plant',	'Generation (GWh)']]

         State  Average MW Per Plant  Generation (GWh)
0   California                  15.3             10826
1      Arizona                  22.5              2550
2       Nevada                  21.6               557
3      Chicago                   7.9               590
4  Connecticut                   5.9               235
5        Texas                  15.6               354
6     New York                   4.1                84
7      Florida                  12.3               453

In [85]:
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

In [86]:
df.sort_values(['Generation (GWh)'])

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
7,Florida,15,535,12.3,453,South
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
1,Arizona,48,1078,22.5,2550,West
0,California,289,4395,15.3,10826,West

In [87]:
df.sort_values(['Installed Capacity (MW)'],ascending=False)

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
7,Florida,15,535,12.3,453,South
3,Chicago,33,261,7.9,590,North
2,Nevada,11,238,21.6,557,West
5,Texas,12,187,15.6,354,South
4,Connecticut,20,118,5.9,235,East
6,New York,13,53,4.1,84,East

In [88]:
# df['Generation (GWh)'].sort_values(ascending=False)[:5]
df.sort_values(['Generation (GWh)'],ascending=False).head()

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
3,Chicago,33,261,7.9,590,North
2,Nevada,11,238,21.6,557,West
7,Florida,15,535,12.3,453,South

In [89]:
df.loc[df.State == 'California'  ]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West

In [90]:
lst = ['California', 'Nevada', 'Arizona', 'Texas']
# filter = df['State'] >'d'

# print(filter)
filter = df['State'].isin(lst) 

df.loc[filter]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
5,Texas,12,187,15.6,354,South

In [91]:
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

In [92]:
df.groupby(by=['Region'])['Number of Solar Plants'].min()

Region
East     13
North    33
South    12
West     11
Name: Number of Solar Plants, dtype: int64

In [93]:
df.groupby(by=['Region'])['Number of Solar Plants'].max()

Region
East      20
North     33
South     15
West     289
Name: Number of Solar Plants, dtype: int64

In [94]:
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

In [95]:
new_row = pd.DataFrame({ 'State':['Carolina'	],
                        'Number of Solar Plants': [148],	
                        'Installed Capacity (MW)': [669]	, 
                        'Average MW Per Plant' : [4.5]	, 
                        'Generation (GWh)': [1162]	,
                        'Region':['North']})

In [96]:
df.loc[len(df)] =[ 'Carolina'	,148	,669,	4.5	,1162	,'North']
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South
8,Carolina,148,669,4.5,1162,North

In [97]:
pd.concat([df,new_row  ],ignore_index=True)

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South
8,Carolina,148,669,4.5,1162,North
9,Carolina,148,669,4.5,1162,North

In [98]:
df.loc[df['State']=='California']

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West

In [99]:
df.iloc[0]

State                      California
Number of Solar Plants            289
Installed Capacity (MW)          4395
Average MW Per Plant             15.3
Generation (GWh)                10826
Region                           West
Name: 0, dtype: object

Q.3Read csv gapminder2007.csv

a.	Display data for all Asian countries

b.	Display top and bottom 15 rows

c.	Show all the rows where life expectancy is more than 50 years and less than 80 years

d.	Show data for India, America and France

e.	Show data for all countries where name starts with ‘A’

f.	Show min/max and mean GDP and Population for each continent

g.	Show population and life expectancy for all countries 

h.	Sort the data by country names (ascending) and GDP (descending)

i.	Find top 20 most populous countries

j.	Delete all rows for a specific country

k.	Change all column names to title case

l.	Change column names: pop to Population, gdpPercap to GDP_Percap

m.	Increase Life Expectancy by 2 years for all African countries

n.	Find all the rows that contain NA values

o.	Fill NA values with 0 for numeric columns

In [100]:
df = pd.read_csv('gapminder2007.csv')
df

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

In [101]:
df[df['continent'] == 'Asia']

                country         pop continent  lifeExp     gdpPercap
0           Afghanistan    31889923      Asia   43.828    974.580338
7               Bahrain      708573      Asia   75.635  29796.048340
8            Bangladesh   150448339      Asia   64.062   1391.253792
18             Cambodia    14131858      Asia   59.723   1713.778686
24                China  1318683096      Asia   72.961   4959.114854
55     Hong Kong, China     6980412      Asia   82.208  39724.978670
58                India  1110396331      Asia   64.698   2452.210407
59            Indonesia   223547000      Asia   70.650   3540.651564
60                 Iran    69453570      Asia   70.964  11605.714490
61                 Iraq    27499638      Asia   59.545   4471.061906
63               Israel     6426679      Asia   80.745  25523.277100
66                Japan   127467972      Asia   82.603  31656.068060
67               Jordan     6053193      Asia   72.535   4519.461171
69     Korea, Dem. Rep.    23301725      Asia   67.297   1593.065480
70          Korea, Rep.    49044790      Asia   78.623  23348.139730
71               Kuwait     2505559      Asia   77.588  47306.989780
72              Lebanon     3921278      Asia   71.993  10461.058680
78             Malaysia    24821286      Asia   74.241  12451.655800
83             Mongolia     2874127      Asia   66.803   3095.772271
87              Myanmar    47761980      Asia   62.069    944.000000
89                Nepal    28901790      Asia   63.785   1091.359778
96                 Oman     3204897      Asia   75.640  22316.192870
97             Pakistan   169270617      Asia   65.483   2605.947580
101         Philippines    91077287      Asia   71.688   3190.481016
109        Saudi Arabia    27601038      Asia   72.777  21654.831940
113           Singapore     4553009      Asia   79.972  47143.179640
119           Sri Lanka    20378239      Asia   72.396   3970.095407
124               Syria    19314747      Asia   74.143   4184.548089
125              Taiwan    23174294      Asia   78.400  28718.276840
127            Thailand    65068149      Asia   70.616   7458.396327
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906

In [102]:
df.head(15)

                   country        pop continent  lifeExp     gdpPercap
0              Afghanistan   31889923      Asia   43.828    974.580338
1                  Albania    3600523    Europe   76.423   5937.029526
2                  Algeria   33333216    Africa   72.301   6223.367465
3                   Angola   12420476    Africa   42.731   4797.231267
4                Argentina   40301927  Americas   75.320  12779.379640
5                Australia   20434176   Oceania   81.235  34435.367440
6                  Austria    8199783    Europe   79.829  36126.492700
7                  Bahrain     708573      Asia   75.635  29796.048340
8               Bangladesh  150448339      Asia   64.062   1391.253792
9                  Belgium   10392226    Europe   79.441  33692.605080
10                   Benin    8078314    Africa   56.728   1441.284873
11                 Bolivia    9119152  Americas   65.554   3822.137084
12  Bosnia and Herzegovina    4552198    Europe   74.852   7446.298803
13                Botswana    1639131    Africa   50.728  12569.851770
14                  Brazil  190010647  Americas   72.390   9065.800825

In [103]:
df.tail(15)

                 country        pop continent  lifeExp     gdpPercap
127             Thailand   65068149      Asia   70.616   7458.396327
128                 Togo    5701579    Africa   58.420    882.969944
129  Trinidad and Tobago    1056608  Americas   69.819  18008.509240
130              Tunisia   10276158    Africa   73.923   7092.923025
131               Turkey   71158647    Europe   71.777   8458.276384
132               Uganda   29170398    Africa   51.542   1056.380121
133       United Kingdom   60776238    Europe   79.425  33203.261280
134        United States  301139947  Americas   78.242  42951.653090
135              Uruguay    3447496  Americas   76.384  10611.462990
136            Venezuela   26084662  Americas   73.747  11415.805690
137              Vietnam   85262356      Asia   74.249   2441.576404
138   West Bank and Gaza    4018332      Asia   73.422   3025.349798
139          Yemen, Rep.   22211743      Asia   62.698   2280.769906
140               Zambia   11746035    Africa   42.384   1271.211593
141             Zimbabwe   12311143    Africa   43.487    469.709298

In [104]:
df[(df['lifeExp'] > 50) & (df['lifeExp'] < 80)] 
# df.where(( (df['lifeExp'] > 50) & (df['lifeExp'] < 80) )).dropna()

                country       pop continent  lifeExp     gdpPercap
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
4             Argentina  40301927  Americas   75.320  12779.379640
6               Austria   8199783    Europe   79.829  36126.492700
7               Bahrain    708573      Asia   75.635  29796.048340
..                  ...       ...       ...      ...           ...
135             Uruguay   3447496  Americas   76.384  10611.462990
136           Venezuela  26084662  Americas   73.747  11415.805690
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906

[110 rows x 5 columns]

In [105]:
df

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

In [106]:
lst = ['India', 'America' , 'France']
df[df['country'].isin(lst)]

   country         pop continent  lifeExp     gdpPercap
44  France    61083916    Europe   80.657  30470.016700
58   India  1110396331      Asia   64.698   2452.210407

In [107]:
df[df['country'].str.startswith('A')]

       country       pop continent  lifeExp     gdpPercap
0  Afghanistan  31889923      Asia   43.828    974.580338
1      Albania   3600523    Europe   76.423   5937.029526
2      Algeria  33333216    Africa   72.301   6223.367465
3       Angola  12420476    Africa   42.731   4797.231267
4    Argentina  40301927  Americas   75.320  12779.379640
5    Australia  20434176   Oceania   81.235  34435.367440
6      Austria   8199783    Europe   79.829  36126.492700

In [108]:
# df.groupby(by=['continent']).agg(['min','max','mean'])
df.groupby(by=['continent']).agg(['min', 'max'])

df.groupby(by=['continent']).agg({
    'gdpPercap':['mean','max','min'],
    'pop':['sum']
})

              gdpPercap                                    pop
                   mean          max           min         sum
continent
Africa      3089.032605  13206.48452    277.551859   929539692
Americas   11003.031625  42951.65309   1201.637154   898871184
Asia       12473.026870  47306.98978    944.000000  3811953827
Europe     25054.481636  49357.19017   5937.029526   586098529
Oceania    29810.188275  34435.36744  25185.009110    24549947

In [109]:



df.groupby('continent').agg(
    mean_gdp= ('gdpPercap','mean'),
    min_gdp = ('gdpPercap','min'),
    max_gdp = ('gdpPercap','max'),
    total_population = ('pop','sum')
)

               mean_gdp       min_gdp      max_gdp  total_population
continent
Africa      3089.032605    277.551859  13206.48452         929539692
Americas   11003.031625   1201.637154  42951.65309         898871184
Asia       12473.026870    944.000000  47306.98978        3811953827
Europe     25054.481636   5937.029526  49357.19017         586098529
Oceania    29810.188275  25185.009110  34435.36744          24549947

In [110]:
df

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

In [111]:
df[['country', 'pop', 'lifeExp']]

                country       pop  lifeExp
0           Afghanistan  31889923   43.828
1               Albania   3600523   76.423
2               Algeria  33333216   72.301
3                Angola  12420476   42.731
4             Argentina  40301927   75.320
..                  ...       ...      ...
137             Vietnam  85262356   74.249
138  West Bank and Gaza   4018332   73.422
139         Yemen, Rep.  22211743   62.698
140              Zambia  11746035   42.384
141            Zimbabwe  12311143   43.487

[142 rows x 3 columns]

In [112]:
df.sort_values(['country'],ascending=True)

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

In [113]:
df.sort_values(['gdpPercap'],ascending=False)

              country        pop continent  lifeExp     gdpPercap
95             Norway    4627926    Europe   80.196  49357.190170
71             Kuwait    2505559      Asia   77.588  47306.989780
113         Singapore    4553009      Asia   79.972  47143.179640
134     United States  301139947  Americas   78.242  42951.653090
62            Ireland    4109086    Europe   78.885  40675.996350
..                ...        ...       ...      ...           ...
52      Guinea-Bissau    1472041    Africa   46.388    579.231743
141          Zimbabwe   12311143    Africa   43.487    469.709298
17            Burundi    8390505    Africa   49.580    430.070692
74            Liberia    3193942    Africa   45.678    414.507341
27   Congo, Dem. Rep.   64606759    Africa   46.462    277.551859

[142 rows x 5 columns]

In [114]:
 
df.sort_values(['country','gdpPercap'], ascending=[True,False])

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

In [115]:
df.sort_values(['pop'],ascending=False).head(20)

              country         pop continent  lifeExp     gdpPercap
24              China  1318683096      Asia   72.961   4959.114854
58              India  1110396331      Asia   64.698   2452.210407
134     United States   301139947  Americas   78.242  42951.653090
59          Indonesia   223547000      Asia   70.650   3540.651564
14             Brazil   190010647  Americas   72.390   9065.800825
97           Pakistan   169270617      Asia   65.483   2605.947580
8          Bangladesh   150448339      Asia   64.062   1391.253792
94            Nigeria   135031164    Africa   46.859   2013.977305
66              Japan   127467972      Asia   82.603  31656.068060
82             Mexico   108700891  Americas   76.195  11977.574960
101       Philippines    91077287      Asia   71.688   3190.481016
137           Vietnam    85262356      Asia   74.249   2441.576404
47            Germany    82400996    Europe   79.406  32170.374420
38              Egypt    80264543    Africa   71.338   5581.180998
42           Ethiopia    76511887    Africa   52.947    690.805576
131            Turkey    71158647    Europe   71.777   8458.276384
60               Iran    69453570      Asia   70.964  11605.714490
127          Thailand    65068149      Asia   70.616   7458.396327
27   Congo, Dem. Rep.    64606759    Africa   46.462    277.551859
44             France    61083916    Europe   80.657  30470.016700

In [116]:
df[df['country']!='China']

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[141 rows x 5 columns]

In [117]:
df.drop(df[  df['country']=='China' ].index   )

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[141 rows x 5 columns]

In [118]:
df.columns = df.columns.str.title()

In [119]:
df.columns

Index(['Country', 'Pop', 'Continent', 'Lifeexp', 'Gdppercap'], dtype='str')

In [120]:
df.rename(columns={'Pop': 'Population' ,'GdpPercap':'GDP_Percap' }, inplace=True)

In [121]:
df

                Country  Population Continent  Lifeexp     Gdppercap
0           Afghanistan    31889923      Asia   43.828    974.580338
1               Albania     3600523    Europe   76.423   5937.029526
2               Algeria    33333216    Africa   72.301   6223.367465
3                Angola    12420476    Africa   42.731   4797.231267
4             Argentina    40301927  Americas   75.320  12779.379640
..                  ...         ...       ...      ...           ...
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906
140              Zambia    11746035    Africa   42.384   1271.211593
141            Zimbabwe    12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

In [122]:
df.loc[df['Continent']=='Africa','Lifeexp'] +=2

In [123]:
df

                Country  Population Continent  Lifeexp     Gdppercap
0           Afghanistan    31889923      Asia   43.828    974.580338
1               Albania     3600523    Europe   76.423   5937.029526
2               Algeria    33333216    Africa   74.301   6223.367465
3                Angola    12420476    Africa   44.731   4797.231267
4             Argentina    40301927  Americas   75.320  12779.379640
..                  ...         ...       ...      ...           ...
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906
140              Zambia    11746035    Africa   44.384   1271.211593
141            Zimbabwe    12311143    Africa   45.487    469.709298

[142 rows x 5 columns]

In [130]:
df.iloc[141] = ['Zimbabwe',None,None,None,None]


df[df.isna().any(axis=1)]

      Country  Population Continent  Lifeexp  Gdppercap
141  Zimbabwe         NaN       NaN      NaN        NaN

In [132]:

df.fillna({col: 0 for col in df.select_dtypes(include='number').columns}, inplace=True)

                Country  Population Continent  Lifeexp     Gdppercap
0           Afghanistan  31889923.0      Asia   43.828    974.580338
1               Albania   3600523.0    Europe   76.423   5937.029526
2               Algeria  33333216.0    Africa   74.301   6223.367465
3                Angola  12420476.0    Africa   44.731   4797.231267
4             Argentina  40301927.0  Americas   75.320  12779.379640
..                  ...         ...       ...      ...           ...
137             Vietnam  85262356.0      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332.0      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743.0      Asia   62.698   2280.769906
140              Zambia  11746035.0    Africa   44.384   1271.211593
141            Zimbabwe         0.0       NaN    0.000      0.000000

[142 rows x 5 columns]