In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# 1.
df = sns.load_dataset('diamonds')
df.head(5)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [10]:
#2.
df.loc[0,'depth'] = 90
df.head(5)

,carat,cut,color,clarity,depth,table,price,x,y,z,"(depth, 0)",0
0,0.23,Ideal,E,SI2,90.0,55.0,326.0,3.95,3.98,2.43,90.0,NaN
1,0.21,Premium,E,SI1,59.8,61.0,326.0,3.89,3.84,2.31,90.0,NaN
2,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31,90.0,NaN
3,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63,90.0,NaN
4,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75,90.0,NaN

In [12]:
#3.
type(df['carat'])

pandas.Series

In [16]:
#4.
df['Quality-color'] = np.nan
df.head(1)

,carat,cut,color,clarity,depth,table,price,x,y,z,"(depth, 0)",0,Quality-color
0,0.23,Ideal,E,SI2,90.0,55.0,326.0,3.95,3.98,2.43,90.0,NaN,NaN

In [29]:
# 5.
print(df.dtypes)
print("No of rows: ",df.shape[0])
print("No of cols: ",df.shape[1])

carat             float64
cut              category
color            category
clarity          category
depth             float64
table             float64
price             float64
x                 float64
y                 float64
z                 float64
(depth, 0)        float64
0                 float64
Quality-color     float64
dtype: object
No of rows:  53941
No of cols:  13

In [30]:
# 6.

In [36]:
#7.
df.rename(columns={'cut':'Cut','color':'Color'})

,carat,Cut,Color,clarity,depth,table,price,x,y,z,"(depth, 0)",0,Quality-color
0,0.23,Ideal,E,SI2,90.0,55.0,326.0,3.95,3.98,2.43,90.0,NaN,NaN
1,0.21,Premium,E,SI1,59.8,61.0,326.0,3.89,3.84,2.31,90.0,NaN,NaN
2,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31,90.0,NaN,NaN
3,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63,90.0,NaN,NaN
4,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75,90.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53936,0.72,Good,D,SI1,63.1,55.0,2757.0,5.69,5.75,3.61,90.0,NaN,NaN
53937,0.70,Very Good,D,SI1,62.8,60.0,2757.0,5.66,5.68,3.56,90.0,NaN,NaN
53938,0.86,Premium,H,SI2,61.0,58.0,2757.0,6.15,6.12,3.74,90.0,NaN,NaN
53939,0.75,Ideal,D,SI2,62.2,55.0,2757.0,5.83,5.87,3.64,90.0,NaN,NaN
depth,90.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN

In [59]:
#8.
df.columns = df.columns.str.upper()

In [60]:
df.columns

Index(['CARAT', 'CUT', 'COLOR', 'CLARITY', 'DEPTH', 'TABLE', 'PRICE', 'X', 'Y',
       'Z', nan, nan, 'QUALITY-COLOR'],
      dtype='str')

In [63]:
#9.
df.drop(columns='COLOR')

,CARAT,CUT,CLARITY,DEPTH,TABLE,PRICE,X,Y,Z,NaN,NaN,QUALITY-COLOR
0,0.23,Ideal,SI2,90.0,55.0,326.0,3.95,3.98,2.43,90.0,NaN,NaN
1,0.21,Premium,SI1,59.8,61.0,326.0,3.89,3.84,2.31,90.0,NaN,NaN
2,0.23,Good,VS1,56.9,65.0,327.0,4.05,4.07,2.31,90.0,NaN,NaN
3,0.29,Premium,VS2,62.4,58.0,334.0,4.20,4.23,2.63,90.0,NaN,NaN
4,0.31,Good,SI2,63.3,58.0,335.0,4.34,4.35,2.75,90.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
53936,0.72,Good,SI1,63.1,55.0,2757.0,5.69,5.75,3.61,90.0,NaN,NaN
53937,0.70,Very Good,SI1,62.8,60.0,2757.0,5.66,5.68,3.56,90.0,NaN,NaN
53938,0.86,Premium,SI2,61.0,58.0,2757.0,6.15,6.12,3.74,90.0,NaN,NaN
53939,0.75,Ideal,SI2,62.2,55.0,2757.0,5.83,5.87,3.64,90.0,NaN,NaN
depth,90.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN